- docs/actor/build.md
- docs/scraping/cheerio_scraper.md
- docs/scraping/index.md
- docs/scraping/introduction.md
- docs/scraping/legacy_phantomjs_crawler.md
- docs/scraping/puppeteer_scraper.md
- docs/scraping/web_scraper.md
Added pages for "Scraping" category with original content. 
Links and images will be fixed all together with other pages in the next PRs.
> Scraping category - content

- docs/actor/input_schema.md
- docs/actor/run.md
- docs/actor/source_code.md
- docs/scheduler.md
- docs/webhooks/ad_hoc_webhooks.md
- docs/webhooks/events.md
I've been getting to know the Apify app over Christmas, before I joined Apify, in order to get to know the platform so I'm not completely lost when I join. I've been reading the user documentation for using the app, and I found some small stylistic issues, grammar issues (mostly missing articles), typos and such. Here I've tried to fix what I noticed, but I haven't gone through the whole documentation systematically, so this is nowhere near a comprehensive fix, just small improvements.
> Small grammar and style fixes

- docs/proxy.md
- docs/proxy/connection_settings.md
The proxy connection settings table was broken, this hotfixes that.
This also fixes the link text on the proxy overview.
This PR just does some hotfixes so the docs are not broken, but the Connection Settings page could maybe use a bit more work, like explaining the username parameter better.
> Proxy: Hotfix Connection settings table

- docs/storage/request_queue.md
The code examples for Request Queues were not working properly, because they didn't use `await`. I've updated them so that they work, and in the process aligned them with the SDK docs for Request Queues.
> Request Queues - fix code examples and align them with SDK docs

- .github/workflows/build.yml
- package.json
I tried to separate linting for Markdown and JS but turned out to be pretty annoying to specify which one to lint each time.
Joining all the lint commands into one
> Simplify linting

- docs/api_v2/api_v2_reference.apib
The new sections are almost the same as Actors->Builds/Runs Collection with different that these get all runs/build for user.
> Api reference: Added list runs and builds endpoints

- docs/actors/development/base_docker_images.md
I hope the new structure won't break anything.
> Update base docker image guide

- docs/api_v2/api_v2_reference.apib
- docs/tutorials/analyze_pages_and_fix_errors.md
It is not aligned with the current state of API regarding the decompression of record. We decompress just records requested with disableRedirect param. We plan to do it, I will merge this after.
> Api reference: Deprecated disableRedirect param and direct-upload kvs endpoint

- docs/web_scraping_101/web_scraping_techniques.md
We removed the Page Analyzer page from the web because it was broken and it requires a bigger rewrite, so I removed the now broken link from the Web Scraping Techniques docs page.
> Remove broken Page Analyzer link from Web Scraping Techniques

- docs/actors/publishing.md
I'd like to add a more descriptive page title for Google, but keep the simpler one in the menu. For example, I’d like to have page title “Publishing actors” on google, but keep just “Publishing” in the menu.
@m-murasovs is this the right way?
> Change page title for "Publishing actors"

- docs/actors/development.md
- docs/actors/examples.md
- docs/actors/paid_actors.md
- docs/actors/running.md
- docs/actors/tasks.md
The previous article was kinda useless and prone to becoming outdated, so I rewrote it to have examples of actors (as the location `/actors/examples` suggests).
Preview here: https://docs.apify.com/actors/examples?version=revamp/examples-cleanup
> Update the actors/examples article

- docs/proxy/connection_settings.md
Added static IPs to proxy connection setting, that can be used as alternative to hostname.
> Proxy: info about static IPs

- docs/api_v2/api_v2_reference.apib
- docs/schedules.md
- docs/storage.md
- docs/storage/dataset.md
- docs/storage/key_value_store.md
- docs/storage/request_queue.md
- docs/tutorials/integrations.md
API docs - I updated only the introduction. It would be cool to also add this info to the console thing, but I couldn't find a way how. Added an info sentence throughout the API reference as a reminder
Docs - updated examples of endpoint URLs to not show the API token as a query parameter and added an info box instead.
closes #219
> Add authentication bearer info for API requests

- docs/actors/development/source_code.md
If you use the link without the protocol, UI throws an error.
> Fix links in Git repo as Source

- docs/storage.md
- docs/storage/dataset.md
- docs/storage/key_value_store.md
- docs/storage/request_queue.md
- docs/web_scraping_101/anti_scraping_techniques.md
Preview: https://docs.apify.com/storage?version=feature/update-api-client
Updates
- Links to apify-client docs and examples of use updated to use the new client
- Removed duplicated information from storage docs and replaced with links to apify-client docs
- Updated a bunch of links to use relative paths for docs instead of absolute
- Updated link texts for better quality
closes #236
> Update links to Apify JS Client and examples

- docs/apify_client_python.md
- docs/cli.md
- docs/sdk.md
This will pull content from the docs in the Python Client repo, similar to how the Javascript client does it. The support on the web is already there.
> Create the API Client for Python page, add it to menu

- README.md
- docs/actors/development/base_docker_images.md
- docs/actors/development/environment_variables.md
- docs/actors/development/input_schema.md
- docs/actors/development/source_code.md
- docs/actors/paid_actors.md
- docs/actors/running.md
- docs/api_v2/api_v2_reference.apib
- docs/storage.md
- docs/storage/dataset.md
- docs/storage/key_value_store.md
- docs/storage/request_queue.md
- docs/tutorials/integrations.md
- docs/web_scraping_101/web_scraping_techniques.md
I've added a bunch of Python client references to places where only the JS client was referenced, and added some Python examples to relevant places.
Python tutorials will come soon in a separate PR.
> Add references to the Python client & Python examples to various places

- src/parser.js
A safety check that makes sure new contributors are less likely to break docs. 
It checks that each folder (with exceptions) has an overview file that's needed for the menu to work properly.
> Add overview file check for folders

- content/docs/actors/limits.md
The problem is that the limit is only 25 for free users and also it's not in `@apify/consts` package like the others, maybe we should add it there?
> feat: Add max concurrent actor runs limit

- content/academy/expert_scraping_with_apify/solutions/saving_stats.md
Without this fix, the code could actually overwrite the "STATS" value before loading the previous state to memory. I also moved the start of the logging to after loading the stats from memory, which makes more sense.
> fix too early persistence

- content/docs/actors/limits.md
Merge this once the new limit is deployed to production.
> feat: Increasing build memory limit to 2 GB

- content/academy/apify_platform/publishing_actors_on_apify_store/monetizing_your_actor.md
Remove "strong" element from the "Price and trial length" section headings and replace it with proper heading priority.
> Fix headings

- content/docs/homepage_content.json
The `actors/publish` was removed from docs but the link on docs homepage remained there. Fixed in this PR
> fix(docs): removed publishing actors link from homepage

- content/docs/actors/tasks.md
- content/docs/storage.md
I think it's all the mentions.
We should add new screenshots, and respective section to actors (it's missing there), once we do the changes with access rights.
> feat: Drop basic settings mentions

- content/docs/actors/limits.md
Increased build timeout to 30 minutes, as per https://github.com/apify/apify-shared-js/pull/357
> feat: Increased actor build timeout

- apify-docs-theme/src/config.js
- src/pages/index.tsx
This removes the "beta" chip next to the Python SDK from the docs header.
> feat: Graduate the Python SDK out of beta

- apify-docs-theme/src/theme/Navbar/Content/index.jsx
- docusaurus.config.js
- sources/academy/index.mdx
- sources/academy/sidebars.js
As per @mtrunkat 's request, this PR slightly changes the academy index page and aligns the behavior with the other projects' instances.
https://user-images.githubusercontent.com/61918049/225900705-63ad614a-28ed-4fff-b91c-c9a9b013c360.mp4
> fix: optional subtitle `to` link, academy sidebar

- sources/platform/actors/development/deployment/source_types.md
This adds documentation for how to make Actor monorepos using the `dockerContextDir` property. I put this to the "Source types" section because that's where it made the most sense right now, but feel free to move it anywhere during the restructuring.
> docs: Add docs for Actor monorepos

- README.md
- sources/academy/platform/deploying_your_code/deploying.md
- sources/academy/platform/expert_scraping_with_apify/managing_source_code.md
- sources/platform/actors/development/source_code.md
- sources/platform/api_v2/api_v2_reference.apib
@mtrunkat I think the API docs should be fine as it only explains that the "Actor source code is comprised of multiple files" which is still true and it stays like this. The Web IDE is only connected to the platform's user interface and I replaced all the mentioning of the `Multiple source files` type in this PR.
Closes [apify-web #2597](https://github.com/apify/apify-web/issues/2597)
> feat: Replaced all mentions about multiple source file with Web IDE

- sources/academy/tutorials/api/run_actor_and_retrieve_data_via_api.md
- sources/platform/api_v2/api_v2_reference.apib
We've updated the max `waitForFinish` value on the backend, but forgot to update it in the docs.
> fix: Update max `waitForFinish` value

- .github/workflows/deploy.yaml
- .github/workflows/invalidate.yaml
- nginx.conf
Other part of PR https://github.com/apify/apify-docs-private/pull/31
> chore: prepare for reusable workflows

- .github/workflows/publish-theme.yaml
This switches the repository to use new secrets from the GitHub organization rather than directly from the GitHub repo, as those are what we want to use where possible.
It's a bit hard to test, so 🤞
> chore: Use new secrets in CI

- sources/platform/integrations/slack.md
Slack needed us to use integration for Slack instead of Slack integration.
> Change wording for integration

- sources/platform/integrations/github.md
We unpublished the old video, this video should replace it. Merge this only when the video goes public.
> fix: Update link to "Deploy changes automatically" video

- sources/platform/storage/index.md
Wanted to link to this in the docs and found out it's missing.
> feat: Mention that ~ can be used without username to access your own stores

- sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
On page [monetizing your actor](https://docs.apify.com/academy/get-most-of-actors/monetizing-your-actor) link to [seo and promotion is broken](https://docs.apify.com/academy/get-most-of-actors/seo-and-promotion). This fix solves this issue.
> docs: fix broken link on monetizing your actor page

- sources/platform/actors/development/quick_start/start_locally.md
- sources/platform/actors/development/quick_start/start_web_ide.md
Apify CLI was accepted into `homebrew-core`, so the installation instructions got a bit simpler.
> chore: Update Apify CLI installation instructions via Homebrew

- sources/platform/api_v2/api_v2_reference.apib
Fixing bug reported on [slack](https://apifier.slack.com/archives/C0L33UM7Z/p1696326166649169): The docs at https://docs.apify.com/api/v2#/reference/actor-runs/update-status-message/update-status-message are wrong, the params (except token) can't be in URL, but must be in PUT body as json
Checked w matej that it is ok as well ✅
> fix(docs): actor status message api params

- sources/platform/storage/request_queue.md
I came across a broken link, so fixing it.
> fix: broken link to Python SDK

- apify-docs-theme/package.json
- package-lock.json
Adds different icon for fragment-level records and expands the breadcrumbs.
See the left pane (results list) in the before / after comparison:
| before | after |
|---|---|
| ![obrazek](https://github.com/apify/docs-search-modal/assets/61918049/ada4fcde-9b58-45c9-875b-7efe5e6ee70d) | ![obrazek](https://github.com/apify/docs-search-modal/assets/61918049/fd99a507-5d7b-4aab-9681-407d2fbfb0be) |
> chore: bump @apify/docs-search-modal version

- sources/platform/api_v2/api_v2_reference.apib
- sources/platform/integrations/webhooks/actions.md
Solving [#12285 from apify-core](https://app.zenhub.com/workspaces/platform-team-5f6454160d9f82000fa6733f/issues/gh/apify/apify-core/12285)-> Add documentation for the new webhook headers and description fields
WIP: the feature needs to be released first but comments are welcome in this stage already :-)
> feat: add info about webhook headers and description

- sources/platform/integrations/actors/integration_ready_actors.md
Originally we thought that using the implicit `payload` will be the way to go, but it turns out that using integration prefill is much nicer.
So in the docs, I'd swap the paragraphs, so the `prefill` comes first.
> feat: Stress prefill section in Actor integration docs

- apify-docs-theme/src/config.js
- package-lock.json
- package.json
- patches/@docusaurus+mdx-loader+2.4.3.patch
Long time no `patch-package` - unfortunately, I didn't come up with a better solution (that wouldn't adding a frontmatter tag to every markdown file in the repo).
Related to apify/apify-web#3159
> docs: integrate new og:image links

- .github/workflows/publish-theme.yaml
Installing the `@apify-packages/ui-components` package only works with the `--legacy-peer-deps` flag (and it broke our CI).
> fix: use `--legacy-peer-deps` in the CI

- .github/workflows/publish-theme.yaml
The theme publishing CI is failing with missing NPM token ([see here](https://github.com/apify/apify-docs/actions/runs/7409319676/job/20159355378)). 
This PR replicates the steps from all the other CI pipelines in the theme publishing one.
> fix: try to fix the theme publishing CI

- apify-docs-theme/package.json
- apify-docs-theme/src/theme.js
- docusaurus.config.js
- package-lock.json
The postcss preset needs to be in the `apify-docs-theme` to fix the styling issues in all of the subprojects.
> fix: propagate the CSS fixes in the theme

- sources/platform/actors/development/quick_start/start_web_ide.md
It should be only one `apify` in each of them
> docs: fix_commands_in_docs

- package-lock.json
- package.json
In the time where I fixed the repo to be usable on windows and actually testing, it seems like the version expired (?) or was deleted. Either way, bumping its patch only (as it uses 0ver and any further bumps technically are major)
> chore: bump apify ui components to an existing version

- src/pages/index.tsx
Fixed Issue: https://github.com/apify/apify-docs/issues/831
> docs: Fix Documentation Links for API Clients Redirect to Incorrect Languages (JavaScript and Python)

- apify-docs-theme/src/theme/custom.css
> fix: improve contrast on inline code blocks and footer links

- sources/platform/api_v2/api_v2_reference.apib
There are two new endpoints, `/actor-builds/<BUILD_ID>/log` and `/acts/<ACTOR_ID>/builds/<BUILD_ID>/log`. This PR adds the corresponding reference.
The endpoints behave the same (modulo authentication) as `/logs/<BUILD_OR_RUN_ID` but due to the limitations of API Blueprint, I couldn't find an easy way to share the reference. Using the same approach as for `/actor-runs/{RUN_ID}/log`, basically just an inline link, also didn't work, as without proper request/response definition, the headlines would not render at all 🤷 Hence a bit of copy-paste seemed like the best approach.
This PR also:
* Removes some outdated information about how the logs endpoint work (they return a standard 200, no redirects)
* Fixes the reference for `/actor-runs/{RUN_ID}/log`
> docs(api): update reference for log endpoints, including the new ones for build

- CONTRIBUTING.md
It's already mentioned in the pre-release section just below but I missed it anyway 🙈
> docs: (even more) explicitly mention Apiary when updating API reference

- sources/platform/api_v2/api_v2_reference.apib
Runs and builds have had dedicated namespaces for a long time (/actor-runs/:run_id and /actor-builds/:build_id). The API reference wasn't making it very clear, so this is an attempt to improve the situation.
Unfortunately, there is no native way for API Blueprint to mark endpoints as deprecated [1], so good old bold text will have to do.
[1] https://github.com/apiaryio/api-blueprint/issues/399
> docs(api): mark run and build endpoints under /acts/:actor_id deprecated

- apify-docs-theme/src/theme/custom.css
> feat: add line numbers to code examples via CSS globally

- README.md
delete information regarding line numbers in muliti-line code fences
add information about proper usage and formatting of docusaurus admonitions
> docs: changes to style guide

- sources/platform/schedules.md
Schedules cannot be shared at the moment.
> docs: remove sharing info from the Schedules page

- apify-docs-theme/src/theme/custom.css
- src/pages/index.module.css
Fixing small headings and descriptions on link cards (e.g. in `/sdk/js/docs/examples`).
This font size comes from docosaurus and the class names have generated suffixes (e.g. `cardTitle_rnsV`) so special selectors had to be used. It was probably caused when changing the rem base size from 16px to 10px.
Reported here: https://apify.slack.com/archives/C0L33UM7Z/p1710937646009279
> fix: examples cards small texts

- .github/workflows/deploy.yaml
- .github/workflows/lychee.yml
- .github/workflows/test.yaml
- apify-docs-theme/src/config.js
- package-lock.json
- package.json
Closes apify/apify-web#3489
Setup Smartlook for Docusaurus. Smartlook token is imported from Doppler.
Not sure abou lychee check though cc @TC-MO
> feat: Setup Smartlook [internal]

- sources/academy/webscraping/puppeteer_playwright/executing_scripts/index.md
I found a lonely semicolon. Let's find him a better place to live, perhaps in some JavaScript code, among his peers.
> fix(academy): remove extraneous semicolon

- sources/academy/webscraping/web_scraping_for_beginners/crawling/finding_links.md
Supersedes https://github.com/apify/apify-docs/pull/896:
- better commit names
- made on top of current `master`, properly using `git` and not a GitHub pencil 😅 
- using inline code per @B4nan's comment https://github.com/apify/apify-docs/pull/896#pullrequestreview-1960109697
> docs: disable unnecessary link

- CONTRIBUTING.md
- README.md
Reading through the contributing guide, I suggest the following improvements:
- Added top-level overview of the docs so that it's clear what "platform" or "academy" means when they're mentioned later
- Some paragraphs under felt like they belong under headings right after them
- Mention of redirects and SEO juice in the README felt oddly specific
I just fixed what I felt like fixing, didn't do a thorough proofreading or any effort to make this document beautiful, as I don't think that's the focus right now.
> feat: improvements to the contributing guide

- sources/platform/storage/request_queue.md
This is part of announcing request queue V2. The features described here were already implemented on backend but not promoted yet.
I will create one more PR with adding new tutorial under [Advanced web scraping academy](https://docs.apify.com/academy/advanced-web-scraping) on How to scraper one request queue from multiple Actor runs.
> feat(request-queue): Extend rq documentation with rqv2 features

- sources/platform/proxy/usage.md
Every now and then, we have a free user that can't use Apify Proxy from inside of the Actors because they're trying to connect to `proxy.apify.com`, not internally through `$APIFY_PROXY_HOSTNAME`, which fails since it's considered an external connection, which is banned on the Free plan.
This improves the Apify Proxy connection instructions to hopefully better explain that when connecting to Apify Proxy from inside an Actor, they should either use the helpers in the `Actor` class in the SDK, or use the `APIFY_PROXY_HOSTNAME`, `APIFY_PROXY_PORT` and `APIFY_PROXY_PASSWORD` environment variables.
Closes #740
> feat: Improve Apify Proxy Usage docs

- .github/CODEOWNERS
According to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners, this should let me know about everything that happens in the Academy. I don't necessarily aim to review everything, but I want to be aware of what's going on. Following the whole repository is too noisy for me.
> chore: add myself to codeowners

- sources/academy/tutorials/node_js/submitting_form_with_file_attachment.md
- sources/academy/webscraping/advanced_web_scraping/scraping_paginated_sites.md
- sources/academy/webscraping/puppeteer_playwright/common_use_cases/logging_into_a_website.md
- sources/academy/webscraping/puppeteer_playwright/common_use_cases/submitting_a_form_with_a_file_attachment.md
- sources/academy/webscraping/puppeteer_playwright/proxies.md
We should not use existing domains or e-mail addresses for examples. The example.com domain is reserved exactly for the purpose of examples, so it can cause no harm to anyone.
> fix: use example.com for examples

- package-lock.json
- src/components/UiLibraryWrapper.tsx
In page /sdk and /api expecially, now the color of the Codeblock texts is working with the color theme of the page
> fix(docs): codeblock correct theme

- sources/academy/tutorials/apify_scrapers/getting_started.md
- sources/academy/webscraping/puppeteer_playwright/common_use_cases/paginating_through_results.md
- sources/academy/webscraping/web_scraping_for_beginners/crawling/filtering_links.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/browser_devtools.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/index.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/node_js_scraper.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/using_devtools.md
- sources/academy/webscraping/web_scraping_for_beginners/index.md
Let's be consistent in what we recommend. Let's recommend the 'official' docs of the web. MDN is a great, unbiased resource for both learning and reference, which is guaranteed to be constantly maintained and updated.
> refactor: link to MDN as a canonical resource

- sources/platform/integrations/langchain.md
They've released a new version of the docs, so I'm updating the link to something which seems to automatically redirect to the latest version: https://python.langchain.com/docs/
Follow up to https://github.com/apify/apify-docs/pull/998/
> refactor: change link to langchain docs

- sources/academy/webscraping/anti_scraping/index.md
Address https://github.com/apify/apify-docs/pull/1013#discussion_r1608010688
> fix: mention the video is outdated, but explain it's still valuable

- sources/platform/integrations/llama.md
Correct Python code examples as the LlamaIndex has changed package structure.
Add one more example of how to load the Apify dataset.
> docs: correct LlamaIndex examples

- nginx.conf
Pages were removed in https://github.com/apify/apify-client-python/pull/232 and https://github.com/apify/apify-client-js/pull/542
> docs: Added redirects for removed api clients pages

- apify-docs-theme/src/theme/custom.css
According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-family#formal_syntax), the `@font-face { font-family }` descriptor can only be a single `string | custom ident`.
Compare to [`font-family` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/font-family#formal_syntax), which can be a priority list.
This discrepancy is causing the tagline in the subprojects to look like ass (fig. 1)
> fix: split the `@font-face` rule to make it valid

- sources/academy/tutorials/node_js/multiple-runs-scrape.md
See the [**Configuration comments**](https://github.com/eslint/eslint-plugin-markdown?tab=readme-ov-file#configuration-comments) section for the markdown ESLint plugin.
Fixes #1068
> fix: silence eslint for new markdown snippets

- nginx.conf
This adds config for handling the `crawlee.dev` domain in the Apify Docs nginx. In the future, we should separate it into a separate nginx.
I've tested it locally and it seems to work when accessing the server with the right `Host` header.
> feat(ci): Add redirects for Crawlee to `nginx.conf`

- sources/platform/actors/development/programming_interface/actor_standby.md
- sources/platform/actors/running/actor_standby.md
This PR changes standby docs headings to H2 so they're displayed in the side bar.
> fix: make standby headings h2

- sources/academy/webscraping/puppeteer_playwright/index.md
I decided not to replace https://blog.arhg.net/2009/10/what-is-headless-browser.html with anything else (e.g. https://en.wikipedia.org/wiki/Headless_browser). I don't think it's necessary to link any external content in the intro. The https://docs.apify.com/academy/web-scraping-for-beginners/crawling/headless-browser lesson already does a good enough job explaining what a headless browser is and has sufficient SEO qualities for the phrase.
Closes https://github.com/apify/apify-docs/issues/957
> fix: rewrite the P&P course intro

- src/pages/index.tsx
Somehow slipped in in my previous PR
> fix: remove cli image dimensions in landing page

- sources/academy/webscraping/scraping_basics_javascript/crawling/pro_scraping.md
Adds a short paragraph with example package.json about the ESM modules.
https://docs.apify.com/academy/web-scraping-for-beginners/crawling/pro-scraping#crawlee-installation
Closes #1063
> fix: mention enabling ESM support

- src/components/Hero/styles.module.css
I haven't found that it was visible somewhere and it caused problems on mobile because it was covering content under it.
reported here:
https://apify.slack.com/archives/C0L33UM7Z/p1722246967335289
> fix: remove hero section gradient

- sources/platform/actors/development/programming_interface/metamorph.md
rework logical flow & structure
added admonitions
> docs: improve metamorph section

- .github/workflows/lychee.yml
Given the amount of false positives we run into at every time when we are adding a new page to docs, it makes sense to change the link checking job to periodic instead of at every PR.
> feat: change link checking to periodic

- .github/workflows/lychee.yml
Somehow this gets called twice in the workflow and the action fails, so I want to try & remove it from here and check if this will make it work
> fix: remove output arg from lychee workflow

- apify-docs-theme/package.json
- package-lock.json
Bumps the `@apify/docs-search-modal` version to include the changes from https://github.com/apify/docs-search-modal/pull/9 .
Completely closes https://github.com/apify/apify-docs/issues/1109
> chore: bump search modal version

- sources/platform/actors/development/programming_interface/actor_standby.md
- sources/platform/actors/development/programming_interface/container_web_server.md
- sources/platform/actors/running/runs_and_builds.md
There were some questions on Discord how to find out if an Actor is started in Standby mode, or normally. This should answer them.
I've also added a tip about Standby in the Container web server docs.
This needs https://github.com/apify/apify-sdk-js/pull/320 released.
> feat: Improve Standby docs

- sources/academy/tutorials/apify_scrapers/getting_started.md
- sources/platform/actors/running/runs_and_builds.md
- sources/platform/storage/usage.md
Change Free Retention "microcopy" -> following the update in console (apify-core repo), link to zenhub issue [here](https://app.zenhub.com/workspaces/platform-team-5f6454160d9f82000fa6733f/issues/gh/apify/apify-core/15694)
I have updated 2 places -> platform: runs and builds, and tutorials: tasks. Please, let me know if there is some other page where it suits well, thanks!
Issue:
> Right now we are (supposed to be) preserving the last 10 runs that a free-user made beyond 30 days. This is for reactivation and debugging purposes. We don't explain this to the user at all, so we should do a better job of that.
Updated sections in docs ⬇️
> docs(platform): update run data retention info

- examples/python-data-scraper/main.py
There is a change in BBC weather which made the previous script obsolete.
> fix: Update main.py

- .github/workflows/deploy.yaml
- .github/workflows/docs.yaml
- .github/workflows/lychee.yml
- .github/workflows/test.yaml
- apify-docs-theme/package.json
- apify-docs-theme/src/config.js
- apify-docs-theme/src/theme.js
- docusaurus.config.js
- package-lock.json
- Remove Smartlook as we no longer use it
- Adding Intercom messenger script to allow AI chat
- added a new variable to the Intercom for this
The growth team has to config properly the messenger window for docs in Intercom and give us a green light to deploy this.
> feat: Remove smartlook and add intercom messenger

- .github/workflows/publish-theme.yaml
Wherever applicable, this PR changes the NPM token to `secrets.NPM_TOKEN` to fix the issue with the `ui-packages` [STILL NOT BEING PUBLIC](https://github.com/apify/apify-docs/actions/runs/10681779569/job/29606166939) (I will never stop hating this.)
This does not replace the last occurrence of the token since I believe we need the old token (`APIFY_SERVICE_ACCOUNT_NPM_TOKEN`) to publish packages in the @apify workspace. This might be a question for @fnesveda - are any of the mentioned GH secrets organization-wide (and do you think we can publish packages with `secrets.NPM_TOKEN`?)
> fix: `publish-theme` action uses `secrets.NPM_TOKEN`

- apify-docs-theme/src/markdown.js
- apify-docs-theme/src/theme.js
`<` and `{` now have special meaning in Docusaurus v3 MDX syntax. In case those characters appear in `changelog.md` file, this breaks the documentation builds.
> fix: escape MDX characters in changelog (Docusaurus v3)

- apify-docs-theme/src/theme/custom.css
> fix: highlight python snippets with `py` language

- package-lock.json
- package.json
Previously there has been a patch to modify front matter in Docusaurus v2, but with migration to Docusaurus v3, this has been moved to a config file and patching is not necessary anymore. The patch itself has been removed from the codebase, but I noticed there are leftovers in form of a dependency and a postinstall script.
Not sure who can review this, so I'm sorry if I asked the wrong people 🙏
> chore: remove patching

- apify-docs-theme/src/theme/MDXComponents/Details.js
- apify-docs-theme/src/theme/MDXComponents/index.js
- sources/academy/webscraping/scraping_basics_python/04_downloading_html.md
- sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
- sources/academy/webscraping/scraping_basics_python/06_locating_elements.md
- sources/academy/webscraping/scraping_basics_python/07_extracting_data.md
- sources/platform/console/index.md
Fixes the mismatch between the `<details>` element pre- and post- the Docusaurus v3 update. Caused by Docusaurus expecting (some?) MDX component names being capitalized. 
Closes #1199
> fix: revert details component rendering to pre-v3 state

- sources/platform/integrations/programming/api.md
This PR fixes wrong wording in the scoped API token documentation, which was using `account level` instead of `account-level`.
This was pointed out by @davidjohnbarton while reviewing the feature [blog post](https://www.notion.so/apify/Blog-post-Introducing-scoped-API-tokens-enhanced-security-and-control-for-your-Apify-integrations-51f57676a6174a3b9c2eeacc49cc3256).
> fix(platform): replace "account level" with "account-level"

- sources/platform/integrations/ai/langchain.md
The link in question was constantly throwing 404's and I cannot find anything similar in langchain docs anymore
> docs: remove dead link in langchain docs

- src/theme/DocItem/Layout/index.js
- src/theme/DocItem/Layout/styles.module.css
Swizzles the `DocItem/Layout` component anew and ports the features (Giscus comments). It solves the issue of moving the layout across different docs pages.
Closes #1193 
https://github.com/user-attachments/assets/a6abdbc3-bd04-429a-b719-73366b8534c7
> fix: stabilize `DocItem/Layout`

- sources/platform/actors/development/actor_definition/input_schema/specification.md
- sources/platform/limits.md
The size was increased in https://github.com/apify/apify-shared-js/pull/478.
> feat: mention larger allowed input schema size

- sources/platform/actors/development/actor_definition/input_schema/specification.md
Add new input schema `editor` values for `string` properties to input schema specification.
This is based on this issue: https://github.com/apify/apify-core/issues/12871 and part of
- Input schema PR: https://github.com/apify/apify-shared-js/pull/476
- (app) Storage input PR: https://github.com/apify/apify-core/issues/12871
This one will be merged as the last one.
> docs: add storages editor to input schema specification

- sources/academy/platform/expert_scraping_with_apify/actors_webhooks.md
- sources/academy/platform/expert_scraping_with_apify/solutions/integrating_webhooks.md
- sources/academy/platform/expert_scraping_with_apify/solutions/rotating_proxies.md
- sources/academy/platform/expert_scraping_with_apify/solutions/saving_stats.md
- sources/academy/platform/expert_scraping_with_apify/solutions/using_storage_creating_tasks.md
- sources/academy/platform/expert_scraping_with_apify/tasks_and_storage.md
- sources/academy/webscraping/puppeteer_playwright/page/interacting_with_a_page.md
- sources/academy/webscraping/puppeteer_playwright/page/page_methods.md
- sources/academy/webscraping/puppeteer_playwright/page/waiting.md
- sources/academy/webscraping/typescript/mini_project.md
- sources/platform/storage/dataset.md
- fix typos, mainly excess**
- update google accept cookies
- update google search element selection
- logical correction
> fix(academy): typos, updates and clarifications

- sources/platform/actors/development/programming_interface/actor_standby.md
- sources/platform/actors/development/programming_interface/environment_variables.md
This PR introduces a new environment variable with Actor standby URL, it also removes the deprecated one for port from the docs and forwards the logic to the web server port env var.
> feat: add standby URL, changes to port unification

- sources/platform/actors/development/builds_and_runs/runs.md
Restructed the content with headings & subheadings
Simplified language for clarity
Changed passive voice to active voice where appropriate
> docs: rewrite runs section

- sources/platform/actors/development/builds_and_runs/state_persistence.md
Restructure content with additional headings & subheadings
Simplified language
Adjusted heading levels
> docs: rewrite state persistence

- apify-docs-theme/src/theme/custom.css
"Solves" misalignment on some pages with too little content.
Before: 
After: 
https://github.com/user-attachments/assets/264e22f9-b073-4140-ab12-a9324f46ee70
---
The issue persists on mid-size desktop (laptop) screens—the fixed-width styling can only be applied on large enough displays; otherwise, the content gets obscured on other pages with actual content.
The moving sidebar is caused by not having enough content (vertically).
> fix: fix content width on pages without much content

- sources/platform/integrations/ai/langchain.md
Update LangChain integration to remove wrong links and information about RAG-Web-Browser
@TC-MO please check English 🙏🏻
> docs: Update LangChain integration to remove wrong links

- sources/platform/actors/running/actor_standby.md
This is a quite important part of sending Standby requests, and it was missing.
I'm having a hard time coming up with some nice formatting, @TC-MO feel free to restructure as you deem fit.
> fix: Add a paragraph about authentication to Actor Standby

- sources/platform/actors/publishing/index.mdx
Restructured the content into sections for better organization
Expanded on the publishing process and stages
Provided more detailed guidance on maintaining public Actors
Added a section on handling breaking changes
Emphasized the importance of clear documentation and testing
Included additional sources for generating ideas for new Actors
Incorporated examples from the Apify blog to illustrate Actor
presentations
Formatted the content in clean Markdown for better readability
> docs: restructure content on index page

- sources/platform/actors/publishing/publish.mdx
Reorganized the content into a more logical structure with clear
sections and headings.
Simplified and clarified the language to improve readability and
comprehension for developers.
Provided step-by-step instructions for accessing publication settings,
writing descriptions and READMEs, and publishing the Actor.
Emphasized the importance of following SEO best practices for
descriptions and READMEs.
> docs: restructure & enhance documentation for Actor publication

- apify-api/openapi/paths/actors/acts@{actorId}@runs@last.yaml
This was caused by the manual edits after the migration, improper use of YAML folded block scalar, and fixed the same way as https://github.com/apify/openapi/pull/111
**After:**
**Before**
> fix: Fixing the broken YAML multi-string in opanapi

- apify-docs-theme/src/theme/custom.css
- docusaurus.config.js
- package-lock.json
- package.json
Styled components are not working in the production build with `@docusaurus/faster`, since babel (nor webpack) is no longer used with that approach.
We need to find a way to make this work, probably with `@rsbuild/plugin-styled-components`, but it didn't work for me now.
Waiting for feedback here: https://github.com/facebook/docusaurus/discussions/10730
> fix: disable `@docusaurus/faster` for now

- sources/platform/storage/request_queue.md
I made some changes in docs regarding the API changes.
* stress out that locking works on the client level and the same as on the run level.
* update code example by separating code into two actors using code tabs
> fix(request-queue): Update request queue locking docs

- sources/platform/actors/development/programming_interface/environment_variables.md
New environment variables are being added to the Actor runtime, better have them documented.
> feat: Add `ACTOR_FULL_NAME` and `ACTOR_BUILD_TAGS` environment variables

- sources/platform/actors/development/quick_start/index.mdx
fix formating
add note instead of codeblock
> docs: fix formatting

- apify-docs-theme/package.json
- apify-docs-theme/src/markdown.js
- package-lock.json
This PR adds actual parsing of the Markdown content instead of using RegExp-based transformations. This mitigates the problems with mismatched token delimiters (nested Markdown links etc.).
Fixes the documentation build in https://github.com/apify/apify-client-js (which in turn unblocks the releases there).
related to https://github.com/facebook/docusaurus/issues/10739
> fix: parse project changelogs with `remark`

- apify-api/openapi/components/schemas/request-queues/GetHeadAndLockResponse.yaml
- apify-api/openapi/components/schemas/request-queues/RequestQueue.yaml
- apify-api/openapi/paths/request-queues/request-queues@{queueId}@head@lock.yaml
- apify-api/openapi/paths/request-queues/request-queues@{queueId}@requests@{requestId}@lock.yaml
Update API reference based on latest changes in API.
> feat(request-queue): Update RQ listAndLock API with latest API changes

- sources/platform/actors/development/actor_definition/dataset_schema/validation.md
Add Python variant example of catching dataset validation errors.
Documents this change: https://github.com/apify/apify-client-python/pull/314
> docs: Add Python variant example of catching dataset validation errors

- sources/platform/actors/development/actor_definition/input_schema/specification.md
Improved docs - see https://apify.slack.com/archives/C010Q0FBYG3/p1734204494460739
> docs: Update specification.md

- nginx.conf
https://crawlee.dev/python/docs now leads to a 404 page, which is not optimal. This should fix that, in a manner consistent with the JS version of the docs
> fix: Add redirect from crawlee.dev/python/docs

- apify-api/openapi/openapi.yaml
- apify-api/openapi/paths/actors/acts@{actorId}@run-sync.yaml
- apify-docs-theme/src/theme/NotFound.jsx
- apify-docs-theme/src/theme/SearchPage/index.js
- apify-docs-theme/src/theme/custom.css
- apify-docs-theme/static/js/custom.js
- docusaurus.config.js
- patches/docusaurus-plugin-openapi-docs+0.0.0-961.patch
- sources/api/sidebars.js
- src/theme/DocSidebarItem/Category/index.js
- fix HTML comments in descriptions
- group sidebar based on group tags
- enable redirects for redoc links (`#tag...`)
- scroll sidebar after redirect
- enable redirects for sidebar categories
- fix wrongly escaped inline code block
- redirect to search page if no match found
> fix: various OpenAPI plugin fixes

- apify-api/openapi/paths/datasets/datasets@{datasetId}@items.yaml
See test runs:
2000 columns - https://console.apify.com/view/runs/zQPSs9IcesvwlZfiw
unlimited items - https://console.apify.com/view/runs/mnPtQvpRJCLtFevg3
I think these changes are a few years old by now so it would be good if someone took a good look.
> fix: correct limits for dataset get items endpoint

- apify-docs-theme/package.json
- apify-docs-theme/src/theme/SearchPage/index.js
- package-lock.json
- package.json
Pins dependencies used from the swizzled `SearchPage` component. The undeclared dependencies were causing the documentation build to fail in the dependent packages (e.g. [here](https://github.com/apify/apify-cli/actions/runs/12755096920/job/35550383965)).
Removes the unused `@apify/docsearch-apify-docs` package from the dependencies.
> chore: switch to algoliasearch v5

- apify-docs-theme/src/config.js
This fixes the lychee 404 errors.
https://github.com/apify/apify-docs/actions/runs/12799427833
> fix: remove trailing slash from internal URL

- package-lock.json
- src/pages/api/index.tsx
- the commands are restructured in a way that the editable part is always at the end of the snippet (especially annoying in multi-line snippets)
- added the saving of the response of the Run to a `run.json `
- added convenience `jq` command to find the dataset in the Actor run response
- removed (imo) unnecessary quotes
- squished the per command line breaks to save lines
Please, try it yourself before merging:
```
echo '{ "searchStringsArray": ["Apify"] }' > input.json
curl -X POST -d @input.json -H 'Content-Type: application/json' \
-s -o >(tee run.json) \
https://api.apify.com/v2/acts/compass~crawler-google-places/runs?token=<YOUR_API_TOKEN>
cat run.json | jq -r .data.defaultDatasetId
curl https://api.apify.com/v2/datasets/<DATASET>/items?token=<YOUR_API_TOKEN>
```
> chore: copy & paste friendly curl API example

- apify-api/openapi/components/tags.yaml
- apify-api/openapi/components/x-tag-groups.yaml
- apify-api/openapi/openapi.yaml
- apify-api/openapi/paths/actors/acts@{actorId}@builds@default.yaml
Recently we released endpoint to get default actor build:
`/v2/acts/:actorId/builds/default`
**This PR updates the documentation to include this endpoint.**
We already had this endpoint:
`/v2/acts/:actorId/builds/:buildId`
I was considering just adding information, that instead of `buildId` `default` can be passed. But since this endpoint is deprecated it does not make sense to me.
@TC-MO  Let me know what do you think?
> feat: added default build endpoint

- apify-docs-theme/src/markdown.js
The recent `unist-util-visit-parents` renovate update broke the `changelogFromRoot` theme option (and therefore e.g. [Apify Python SDK changelog](https://docs.apify.com/sdk/python/docs/changelog)). Even though the `unist` package claims to be ESM-only, this fix seems to remedy the issues.
> fix: use correct `unist-util-visit-parents` imports

- apify-api/openapi/openapi.yaml
Add full schema link to API docs introductory paragraph
> docs: add full schema link

- sources/platform/actors/development/programming_interface/actor_standby.md
This PR adds documentation for readiness probe in Actor standby along with code examples that show example handling of the readiness requests.
> feat: add standby readiness probe docs

- sources/platform/integrations/ai/haystack.md
- sources/platform/integrations/ai/langchain.md
- sources/platform/integrations/ai/langgraph.md
- fix and update [LangChain Apify integration docs](https://docs.apify.com/platform/integrations/langchain) to use our new [langchain-apify](https://github.com/apify/langchain-apify) integration package.
- add docs on how to use Apify tools with agents using [LangGraph](https://www.langchain.com/langgraph)
> feat: update langchain apify

- sources/platform/actors/development/builds_and_runs/state_persistence.md
We've recently added support to speed up Actor migrations by rebooting the run when it's migrating. This adds docs about that, with code examples.
The support for this in the Apify SDK is not released yet, it'll go out in the next SDK release, I'll only merge the docs then.
> feat: Add "Speeding up migrations" section to "State persistence"

- apify-docs-theme/src/markdown.js
In a recent `eslint` formatting PR (#1439), we changed the `void` returns to `return 0`. This causes `unified` to loop indefinitely in some cases (the visitor is expected to return `true / false` or **index of the next sibling** to be visited).
This PR makes use of the exported `CONTINUE` symbol (alias for `true`) and the more verbose return syntax.
Fixes the stalling documentation builds in Apify SDK for Python.
> fix: remove possible infinite loop in the changelog transformation

- sources/platform/security.md
Added a note encouraging users to avoid publicly disclosing vulnerabilities until they have been addressed. This helps ensure security issues are properly evaluated and mitigated before exposure to potential exploitation.
> feat: add responsible disclosure guidelines to security page

- sources/platform/integrations/programming/webhooks/actions.md
We have started sending webhooks from the Apify platform through a predefined list of static IP addresses. This enables users (typically enterprise customers) who have the webhook destinations behind a firewall to whitelist these IP addresses in their firewall, and allow the delivery of these webhooks.
> feat: Mention that webhooks are sent through select static IPs

- apify-api/openapi/components/schemas/datasets/Dataset.yaml
- apify-api/openapi/components/schemas/key-value-stores/KeyValueStore.yaml
- apify-api/openapi/components/schemas/request-queues/RequestQueue.yaml
Recently, we added a new field, `consoleUrl`, to storage responses (GET, PUT, POST).
This PR updates the documentation to include the `consoleUrl` field in:
- Datasets
- Key-Value Stores
- Request Queues
> chore: add consoleUrl field to storages

- sources/academy/platform/get_most_of_actors/actor_basics/how-to-create-actor-readme.md
- sources/academy/platform/get_most_of_actors/actor_basics/name-your-actor.md
- sources/academy/platform/get_most_of_actors/promote_your_actor/parasite_seo.md
- sources/academy/platform/get_most_of_actors/store_basics/how_store_works.md
- sources/academy/platform/get_most_of_actors/store_basics/how_to_build_actors.md
add missing link to issues tab
remove section about getting featured on Apify
removed SEO guide with locked access
> docs: fix broken links in Actor marketing playbook

- apify-api/openapi/components/schemas/actor-runs/RunStats.yaml
The value can be omitted for runs started without input.
> docs: Fix ActorRunStats OpenAPI schema

- .github/CODEOWNERS
- this is so that @netmilk and somebody from Tooling team (I volunteer as tribute) know when something changes in the OpenAPI spec
- we should also add somebody from the platform team - @fnesveda, what do you think?
> chore: Set up CODEOWNERS for openapi specs

- sources/academy/platform/get_most_of_actors/actor_basics/how-to-create-actor-readme.md
> docs: small errors and stylistics

- apify-docs-theme/src/markdown.js
[Changes in `require` / `esm` implementation](https://github.com/nodejs/node/releases/tag/v22.12.0) in the recent Node 22 versions caused the changelog transformation to fail on Node >=22.12. 
This should fix the missing changelogs in all the dependent projects (`apify-sdk-python`, `client-js`, `client-python`).
> fix: import `unified` plugins correctly in Node `>=22.12`

- .github/workflows/docs.yaml
- .github/workflows/lychee.yml
- .github/workflows/openapi.yaml
- .github/workflows/publish-theme.yaml
- .github/workflows/test.yaml
- .npmrc
- CONTRIBUTING.md
- docusaurus.config.js
- package-lock.json
- package.json
- src/components/ActionCard/ActionCard.tsx
- src/components/ActorTemplates/ActorTemplates.tsx
- src/components/Button.tsx
- src/components/CardWithIcon/CardWithIcon.tsx
- src/components/Heading.tsx
- src/components/OpenSourceCards/OpenSourceCards.tsx
- src/components/PlainCard/PlainCard.tsx
- src/components/SdkSection/SdkSection.tsx
- src/components/Section/Section.tsx
- src/components/Tabs.tsx
- src/components/Text.tsx
- src/components/UiLibraryWrapper.tsx
- src/pages/api/index.tsx
- src/pages/index.tsx
- src/pages/open-source/index.tsx
- src/pages/sdk/index.tsx
This PR adopts the new `@apify/ui-components` library which was previously available only on our private NPM registry. This means we should be finally open source again - and people from outside apify org should be able to run things locally (as well as PR checks should work again on PRs from forks).
I also did a full lockfile update to be sure we have no duplicates or dated dependencies after the update.
> chore: use `@apify/ui-components` package from NPM

- apify-api/openapi/openapi.yaml
- apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@runs@last.yaml
add missing actor-tasks endpoint
add TODO's to be discussed regarding categorization & linking add missing endpoint to openapi.yaml
> docs: add missing actor-tasks endpoint

- sources/platform/actors/development/programming_interface/actor_standby.md
- sources/platform/actors/running/actor_standby.md
This PR adds info about the request timeout for standby:
- 5 minutes as the total timeout
- 2 minutes as the timeout for "run choosing", only mentioned for devs
> docs: add standby request timeout info

- apify-api/openapi/openapi.yaml
- apify-api/openapi/paths/key-value-stores/key-value-stores@{storeId}@keys.yaml
remove admonition with link to old docs
fix link to pagination
> docs: update API docs

- .github/styles/config/vocabularies/Docs/accept.txt
- sources/academy/homepage_content.json
- sources/academy/platform/expert_scraping_with_apify/actors_webhooks.md
- sources/academy/platform/expert_scraping_with_apify/index.md
- sources/academy/webscraping/advanced_web_scraping/crawling/sitemaps-vs-search.md
- sources/academy/webscraping/advanced_web_scraping/index.md
- sources/academy/webscraping/anti_scraping/mitigation/using_proxies.md
- sources/academy/webscraping/puppeteer_playwright/index.md
- sources/academy/webscraping/puppeteer_playwright/page/interacting_with_a_page.md
- sources/academy/webscraping/scraping_basics_javascript/challenge/modularity.md
- sources/academy/webscraping/scraping_basics_javascript/challenge/scraping_amazon.md
- sources/academy/webscraping/scraping_basics_javascript/crawling/exporting_data.md
- sources/academy/webscraping/scraping_basics_javascript/crawling/index.md
- sources/academy/webscraping/scraping_basics_javascript/crawling/recap_extraction_basics.md
- sources/academy/webscraping/scraping_basics_javascript/data_extraction/node_continued.md
- sources/academy/webscraping/scraping_basics_javascript/data_extraction/save_to_csv.md
- sources/academy/webscraping/scraping_basics_javascript/index.md
- sources/academy/webscraping/typescript/enums.md
Rename the JS course from "Web scraping for beginners" to "Web scraping basics for JavaScript devs", so that it is aligned with the Python course and the design described in https://github.com/apify/apify-docs/issues/1015
This change attempts to isolate the change to the course name only. The name appears at many places which could be improved or which are questionable, but this change is not intended to be a complete overhaul of the course.
> feat: rename the JS course

- sources/academy/webscraping/scraping_basics_python/01_devtools_inspecting.md
- sources/academy/webscraping/scraping_basics_python/02_devtools_locating_elements.md
- sources/academy/webscraping/scraping_basics_python/03_devtools_extracting_data.md
- sources/academy/webscraping/scraping_basics_python/04_downloading_html.md
- sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
- sources/academy/webscraping/scraping_basics_python/06_locating_elements.md
- sources/academy/webscraping/scraping_basics_python/07_extracting_data.md
- sources/academy/webscraping/scraping_basics_python/08_saving_data.md
- sources/academy/webscraping/scraping_basics_python/09_getting_links.md
- sources/academy/webscraping/scraping_basics_python/10_crawling.md
- sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
- sources/academy/webscraping/scraping_basics_python/12_framework.md
- sources/academy/webscraping/scraping_basics_python/13_platform.md
Fixes https://github.com/apify/apify-docs/issues/1247. The change seems to work just fine and it doesn't seem to interfere with anything.
> chore: infer 'sidebar_position' from the filename

- sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
Thanks @rizkil for reporting the issue! In the future this should be prevented by https://github.com/apify/apify-docs/issues/1243. I checked other exercises and I couldn't find any other which are based on the formula1.com website, so this is hopefully the only one which got broken.
> fix: exercises using the F1 website got outdated

- sources/platform/collaboration/access_rights.md
Remove outdated info - all users have username
> feat: Update access_rights.md

- sources/academy/webscraping/scraping_basics_python/12_framework.md
Only for the framework lesson, previously discussed here https://github.com/apify/apify-docs/pull/1303#pullrequestreview-2473520225
> feat: add type hints

- sources/academy/homepage_content.json
- sources/academy/webscraping/anti_scraping/index.md
- sources/academy/webscraping/api_scraping/index.md
- sources/academy/webscraping/puppeteer_playwright/index.md
- sources/academy/webscraping/scraping_basics_python/index.md
Fixes https://github.com/apify/apify-docs/issues/1319! 🎉 Known issues:
- The homepage image for the course card is the same as for the JS course. I think later on we should ask a designer to provide new images which would distinguish the JS and Py course.
- https://github.com/apify/apify-docs/pull/1568 - TBD in parallel with this PR
- https://github.com/apify/apify-docs/issues/1570 - not essential, can be simply added later on
- https://github.com/apify/apify-docs/issues/1243 - not a priority right now
> feat: publish the Python course on the Academy homepage

- apify-api/openapi/components/schemas/users/EffectivePlatformFeature.yaml
- apify-api/openapi/components/schemas/users/EffectivePlatformFeatures.yaml
- apify-api/openapi/components/schemas/users/UserPrivateInfo.yaml
https://api.apify.com/v2/users/me?token=<TOKEN>
> fix(api-schema): add missing 'effectivePlatformFeatures', 'createdAt', 'isPaying' to UserPrivateInfo

- sources/platform/integrations/workflows-and-notifications/make/ai-crawling.md
- sources/platform/integrations/workflows-and-notifications/make/instagram.md
fix missing space before parenthesis
fix typo in instagram make app doc
> docs: fix typos

- apify-api/openapi/paths/logs/logs@{buildOrRunId}.yaml
Documents the `raw` query param from the API's [log](https://github.com/apify/apify-core/blob/94b7ce60a0850fa4d9bd62343bebec86bea5a796/src/api/src/routes/logs/log.js#L30) function.
> docs: document `raw` query param in `logs`

- apify-api/openapi/paths/actor-builds/actor-builds@{buildId}@openapi.json.yaml
- apify-api/openapi/paths/actors/acts@{actorId}@builds@default.yaml
This PR adds correct links to JS & Python clients for:
- `/v2/actor-builds/:buildId/openapi.json`
- `/v2/acts/:actorId/builds/default`
> chore: add links to JS & python clients

- sources/platform/actors/development/actor_definition/actor_json.md
Document the `webServerSchema` field in `actor.json`:
> docs: add webServerSchema field in actor definition

- sources/platform/actors/development/actor_definition/input_schema/specification.md
The `additionalProperties` is completely missing in the input schema specification.
> docs: add additionalProperties to input schema specification

- apify-docs-theme/src/config.js
- docusaurus.config.js
If the `NO_INDEX` environment variable is used during build, the [`noIndex` Docusaurus config](https://docusaurus.io/docs/api/docusaurus-config#noIndex) will be used and the docs will be built so that they're not indexable by search engines.
> feat: Add configurable search engine indexing behavior [internal]

- sources/academy/platform/deploying_your_code/deploying.md
- sources/academy/platform/deploying_your_code/docker_file.md
- sources/academy/platform/deploying_your_code/index.md
- sources/academy/platform/deploying_your_code/input_schema.md
- sources/academy/platform/deploying_your_code/inputs_outputs.md
- sources/academy/platform/deploying_your_code/output_schema.md
Rename to avoid confusion & make titles more action-oriented
> docs: rename Academy articles

- sources/platform/integrations/ai/mcp.md
With the near future update of the MCP server, tools for adding and removing Actors will be enabled by default.
> fix: MCP server can add and remove Actors as default behavior

- sources/academy/webscraping/scraping_basics_javascript2/09_getting_links.md
- sources/academy/webscraping/scraping_basics_javascript2/10_crawling.md
- sources/academy/webscraping/scraping_basics_javascript2/11_scraping_variants.md
- sources/academy/webscraping/scraping_basics_python/08_saving_data.md
- sources/academy/webscraping/scraping_basics_python/09_getting_links.md
- sources/academy/webscraping/scraping_basics_python/10_crawling.md
- sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
When working on https://github.com/apify/apify-docs/pull/1584 I realized it'd be better if the lesson started with JSON and continued with CSV, not the other way.
In Python it doesn't matter and in JavaScript it's easier to start with JSON, which is built-in, and only then move to CSV, which requires an additional library. So for the sake of having both lessons aligned, I want to change the order in the Python lesson, too.
So most of the diff is just the two sections reversed, and the two exercises reversed. I made only a few additional changes to the wording.
> fix: re-order JSON and CSV in Python lessons

- apify-docs-theme/src/theme/custom.css
fixes navbar subtitle width that wouldn't fit for JS/Python client subpages due to bigger paddings in new design uplift
> fix: navbar subtitle width

- sources/platform/actors/development/actor_definition/actor_json.md
Add a missing dot prefix to indicate the hidden `.actor` folder containing `actor.json`.
> docs: fix typo in actor_json.md

- sources/platform/actors/development/programming_interface/environment_variables.md
Add documentation for `APIFY_USER_IS_PAYING` environmental variable.
- This is followup of these changes:
- https://github.com/apify/apify-sdk-js/pull/415
- https://github.com/apify/apify-shared-python/pull/40
- https://github.com/apify/apify-sdk-python/pull/507
> docs: add `APIFY_USER_IS_PAYING` env var documentation

- src/plugins/docusaurus-plugin-segment/index.js
convert the error to a warning, to allow local development without the key
> fix: allow builds without the segment API key

- nginx.conf
Redirects the traffic from `/sdk/js/versions` to `/sdk/js/docs/changelog`
Connected to https://github.com/apify/apify-sdk-js/pull/416
Alternatively, we don't have to merge this (to keep the `nginx` conf clean), the `versions` page had likely 0 traffic (only linked from the sitemap).
> docs: redirect SDK JS `versions` page to changelog

- sources/platform/security.md
We’ve been receiving an increasing number of questions regarding financial compensation for submitted security reports, so adding this to clarify it.
> docs: add note on vulnerability disclosure policy rewards

- sources/academy/webscraping/scraping_basics_javascript2/04_downloading_html.md
- sources/academy/webscraping/scraping_basics_javascript2/05_parsing_html.md
- sources/academy/webscraping/scraping_basics_javascript2/06_locating_elements.md
- sources/academy/webscraping/scraping_basics_javascript2/07_extracting_data.md
- sources/academy/webscraping/scraping_basics_javascript2/08_saving_data.md
- sources/academy/webscraping/scraping_basics_javascript2/09_getting_links.md
- sources/academy/webscraping/scraping_basics_javascript2/10_crawling.md
- sources/academy/webscraping/scraping_basics_javascript2/11_scraping_variants.md
- sources/academy/webscraping/scraping_basics_javascript2/12_framework.md
- sources/academy/webscraping/scraping_basics_javascript2/13_platform.md
- sources/academy/webscraping/scraping_basics_javascript2/index.md
A part of https://github.com/apify/apify-docs/pull/1584
> feat: update the course intro and all lesson intros of the JS2 course to be about JavaScript

- sources/platform/actors/running/actor_standby.md
Document the default rate limit of 2000 reqs per sec for standby Actor incoming request.
> docs: standby incoming requests rate limit

- apify-api/openapi/components/securitySchemes/apiKey.yaml
- apify-api/openapi/components/securitySchemes/apiKeyActorBuilds.yaml
- apify-api/openapi/components/securitySchemes/apiKeyQueueId.yaml
- apify-api/openapi/components/securitySchemes/apiKeyStoreId.yaml
- apify-api/openapi/components/securitySchemes/httpBearer.yaml
- apify-api/openapi/components/securitySchemes/httpBearerActorBuilds.yaml
- apify-api/openapi/components/securitySchemes/httpBearerQueueId.yaml
- apify-api/openapi/components/securitySchemes/httpBearerStoreId.yaml
- apify-api/openapi/openapi.yaml
- apify-api/openapi/paths/actor-builds/actor-builds@{buildId}.yaml
- apify-api/openapi/paths/actor-builds/actor-builds@{buildId}@openapi.json.yaml
- apify-api/openapi/paths/actors/acts@{actorId}@builds@default.yaml
- apify-api/openapi/paths/actors/acts@{actorId}@builds@{buildId}.yaml
- apify-api/openapi/paths/actors/acts@{actorId}@builds@{buildId}@openapi.json.yaml
- apify-api/openapi/paths/datasets/datasets@{datasetId}@items.yaml
- apify-api/openapi/paths/key-value-stores/key-value-stores@{storeId}.yaml
- apify-api/openapi/paths/key-value-stores/key-value-stores@{storeId}@keys.yaml
- apify-api/openapi/paths/key-value-stores/key-value-stores@{storeId}@records@{recordKey}.yaml
- apify-api/openapi/paths/request-queues/request-queues@{queueId}.yaml
- apify-api/openapi/paths/request-queues/request-queues@{queueId}@requests@{requestId}.yaml
merge apiKey & htttpBearer to one per
make sure all endpoints refer to correct security
adjust descriptions
add admonitions
> docs: change security description within API docs

- sources/academy/webscraping/scraping_basics_javascript2/02_devtools_locating_elements.md
- sources/academy/webscraping/scraping_basics_python/02_devtools_locating_elements.md
A part of https://github.com/apify/apify-docs/pull/1584
> feat: update the DevTools 2 lesson of the JS2 course to be about JavaScript

- package-lock.json
- sources/platform/actors/development/quick_start/index.mdx
- sources/platform/actors/development/quick_start/start_locally.md
- sources/platform/actors/development/quick_start/start_web_ide.md
The PR refactors the Quick Start section of the platform documentation. The main changes involve:
- Adding clear steps on what to do; this is generally a best practice in quick start documentation
- Simplifying the content (the goal should be to show value to new users as quickly as possible)
- Adding missing information and links (templates, etc.)
> docs: Improve Quick Start section in the platform docs

- sources/platform/actors/development/index.md
- sources/platform/console/index.md
- sources/platform/integrations/actors/index.md
- sources/platform/storage/usage.md
This is a follow up for the PR: https://github.com/apify/apify-docs/pull/1751. Some titles need to improve as I did not wait for @TC-MO - sorry!
> docs: Fix titles based on discussion

- apify-docs-theme/package.json
- apify-docs-theme/src/theme/SearchBar/index.js
- package-lock.json
Also opens the kapa widget with the AI chat tab first.
Closes #1745
> fix: support `cmd+k` to open the search modal

- sources/academy/webscraping/scraping_basics_javascript2/04_downloading_html.md
- sources/academy/webscraping/scraping_basics_javascript2/05_parsing_html.md
A part of https://github.com/apify/apify-docs/pull/1584
> feat: update the downloading lesson of the JS2 course to be about JavaScript

- sources/platform/actors/development/builds_and_runs/index.md
Noticed https://docs.apify.com/platform/actors/development/builds-and-runs#running-an-actor has broken md
> fix: Broken markdown in builds and runs section

- sources/platform/actors/development/actor_definition/dataset_schema/index.md
Fix the type of the output schema fields.
- `transformation.omit` and `transformation.unwind` should be an array of strings, as Worker enforces that.
> fix: wrong output schema field types

- sources/platform/limits.md
Update plan names to reflect current naming
Remove heading anchors
> docs: update plan names

- apify-api/openapi/components/schemas/datasets/Dataset.yaml
- apify-api/openapi/components/schemas/key-value-stores/KeyValueStore.yaml
- apify-api/openapi/components/schemas/key-value-stores/ListOfKeysResponse.yaml
This PR updates updates storage responses:
- GET dataset has `itemsPublicUrl` and `urlSigningSecretKey`
- GET KV store has `keysPublicUrl` and `urlSigningSecretKey`
- Get KV store keys, item has `recordPublicUrl`
> docs: add new signed URL fields to dataset & key-value store

- apify-api/openapi/paths/actor-runs/actor-runs.yaml
- apify-api/openapi/paths/actor-tasks/actor-tasks@{actorTaskId}@runs.yaml
- apify-api/openapi/paths/actors/acts@{actorId}@runs.yaml
Following endpoints were updated in [PR #22366](https://github.com/apify/apify-core/pull/22240):
- `/v2/acts/:actorId/runs`
- `/v2/actor-runs`
- `v2/actor-tasks/:actorTaskId/runs`
The change extends the status parameter to support a comma-separated list of multiple statuses, allowing filtering based on the selected values.
This update reflects the changes in the documentation for the status parameter.
> feat: enable comma-separated status filtering across updated endpoints

- .vale.ini
- sources/platform/actors/publishing/monetize.mdx
add new note to monetization documentation
add new ignoredscope to .vale.ini
> docs: add note about negative profit isolation

- sources/platform/storage/dataset.md
- sources/platform/storage/index.md
- sources/platform/storage/request_queue.md
- sources/platform/storage/usage.md
- src/components/StoragePricingCalculator/StoragePricingCalculator.module.css
- src/components/StoragePricingCalculator/index.jsx
add new component to calculate storage pricing
style component
add it to Storage usage page
add link to calculator on Storage index page
> docs: add storage pricing calculator component

- CONTRIBUTING.md
There is an incorrect branch specified in the guidelines: instead of `master`, there is `main` branch mentioned, which does not exist.
> chore: specify correct default branch in CONTRIBUTION.md

- apify-docs-theme/src/theme/Layout/index.jsx
- apify-docs-theme/static/js/custom.js
- sources/platform/integrations/ai/mcp.md
Always clear cache when on MCP page to help with redirect issues.
Previously, mcp.apify.com had a 301 redirect to this docs page, which was wrong.
Many users have this redirect cached in their browsers, so they can't access the new MCP UI.
This helps with their cached redirect, allowing them to access mcp.apify.com
@B4nan is there is a better place to put the code than in the src/theme/layout? 
Kudos to @JJetmar 
FYI @MQ37 
close https://github.com/apify/apify-mcp-server/issues/129
close https://github.com/apify/ai-team/issues/33
EDIT: Remove this fix after some time: https://github.com/apify/apify-docs/issues/1802
> fix: Always clear cache when on MCP page to help with redirect issue

- sources/academy/webscraping/scraping_basics_javascript2/08_saving_data.md
- sources/academy/webscraping/scraping_basics_python/08_saving_data.md
Part of https://github.com/apify/apify-docs/pull/1584
> feat: update the saving lesson of the JS2 course to be about JavaScript

- .github/workflows/lychee.yml
Recent `lychee` updates (`0.19.0` and above) improve Lychee and align it more with the HTML spec. This, however, also means that Lychee now finds 2000+ "broken" links due to incorrect setup in this repo. 
Since fragment links inside of docs.apify.com are checked internally with Docusaurus anyway, this PR disables the fragment link checker in Lychee.
> chore: skip fragment link checks with lychee

- sources/academy/webscraping/scraping_basics_javascript2/05_parsing_html.md
- sources/academy/webscraping/scraping_basics_javascript2/index.md
- sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
Part of https://github.com/apify/apify-docs/pull/1584, fixes https://github.com/apify/apify-docs/issues/1648
⚠️ 🐍 Includes respective changes also to the original `scraping_basics_python` lesson
> feat: update the parsing lesson of the JS2 course to be about JavaScript

- sources/platform/actors/publishing/monetize.mdx
The PR adds a link to the API docs to get PPE event names. It is a follow-up from [the discussion in Slack](https://apify.slack.com/archives/C010Q0FBYG3/p1756045327790319).
One of the suggested solutions was to also provide the full JSON, but I decided not to do it. The main reason is that if the API payload changes, we might forget to update the JSON in the pricing page. This could lead to more confusion. Therefore, I would just keep the link to the API page as the single source of truth.
> docs: Add link to API for PPE event names

- sources/platform/integrations/ai/mcp.md
New spec: https://www.notion.so/apify/MCP-Server-240f39950a22800d9019f92ed7e8da93?source=copy_link#255f39950a2280b09f7bca2bdd400071
Refactored the page to be more consistent with the https://github.com/apify/apify-mcp-server.
**Merge after new mcp.apify.com release**
> docs(mcp): update to reflect the new configuration spec

- sources/academy/webscraping/scraping_basics_python/07_extracting_data.md
- sources/academy/webscraping/scraping_basics_python/08_saving_data.md
- sources/academy/webscraping/scraping_basics_python/09_getting_links.md
- sources/academy/webscraping/scraping_basics_python/10_crawling.md
- sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
- sources/academy/webscraping/scraping_basics_python/12_framework.md
- sources/academy/webscraping/scraping_basics_python/13_platform.md
This makes the code simpler and the lessons are closer to their JavaScript counterparts. Also the real world practice uses cents, e.g. the Stripe API and others.
> feat: scrape prices as cents, avoid Decimal

- apify-docs-theme/src/theme/DocItemContent/index.js
Related to: https://github.com/apify/workflows/issues/215
> fix: Disable LLM buttons on changelog pages

- sources/academy/webscraping/scraping_basics_javascript2/13_platform.md
- sources/academy/webscraping/scraping_basics_python/13_platform.md
Part of https://github.com/apify/apify-docs/pull/1584
----
⚠️ 🐍 This PR contains also changes to the Python course, to keep the lessons consistent and synced.
> feat: update the platform lesson of the JS2 course to be about JavaScript

- sources/academy/webscraping/scraping_basics_javascript2/11_scraping_variants.md
- sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
Part of https://github.com/apify/apify-docs/pull/1584
----
⚠️ 🐍 This PR contains also a small change to the Python course, to keep the lessons consistent and synced.
> feat: update the scraping variants lesson of the JS2 course to be about JavaScript

- sources/academy/webscraping/scraping_basics_javascript2/12_framework.md
- sources/academy/webscraping/scraping_basics_python/12_framework.md
Part of https://github.com/apify/apify-docs/pull/1584
----
⚠️ 🐍 This PR contains also changes to the Python course, to keep the lessons consistent and synced.
> feat: update the framework lesson of the JS2 course to be about JavaScript

- sources/academy/webscraping/scraping_basics_javascript2/06_locating_elements.md
- sources/academy/webscraping/scraping_basics_javascript2/07_extracting_data.md
- sources/academy/webscraping/scraping_basics_javascript2/08_saving_data.md
- sources/academy/webscraping/scraping_basics_javascript2/09_getting_links.md
- sources/academy/webscraping/scraping_basics_javascript2/10_crawling.md
- sources/academy/webscraping/scraping_basics_javascript2/11_scraping_variants.md
- sources/academy/webscraping/scraping_basics_javascript2/12_framework.md
Also fixes a few bugs I noticed when trying out the code.
> refactor: use for/of and .toArray() when looping over Cheerio selections

- sources/academy/webscraping/scraping_basics_javascript2/09_getting_links.md
- sources/academy/webscraping/scraping_basics_javascript2/10_crawling.md
- sources/academy/webscraping/scraping_basics_javascript2/11_scraping_variants.md
> fix: missing semicolon

- sources/academy/webscraping/scraping_basics_javascript2/08_saving_data.md
- sources/academy/webscraping/scraping_basics_python/08_saving_data.md
- sources/academy/webscraping/scraping_basics_python/12_framework.md
Let the machine do the counting!
> style: use Markdown's automatic numbering

- .github/styles/Apify/Capitalization.yml
Attempt to help @TC-MO to break down https://github.com/apify/apify-docs/pull/1890/ to smaller self-contained pieces.
> refactor: simplify how capitalization works

- sources/platform/integrations/workflows-and-notifications/bubble.md
Fixed missing code block closure in Bubble integration documentation
This PR fixes a formatting issue in the Bubble integration documentation where a JSON code block was not properly closed. The missing closing code block marker (```) has been added after line 109, ensuring the proper rendering of the documentation and preventing subsequent content from being incorrectly formatted as code.
This minor adjustment makes the rest of the doc more readable and follows the Markdown format.
> fix: bubble integration doc

- nginx.conf
- sources/platform/integrations/ai/llama.md
- sources/platform/integrations/index.mdx
Corrected spelling of 'LlamaIndex' and updated slug.
> feat(docs): Fix LlamaIndex spelling and slug in documentation

- package-lock.json
- package.json
- scripts/indentLlmsFile.mjs
closes: https://github.com/apify/apify-docs/issues/1883
Indentation of `llms.txt` based on the route segments and route depth.
Unfortunately, the depth param from the Docusaurus plugin is not for indenting. So the custom script had to be done.
> feat: Improve llms.txt file indentation

- sources/platform/actors/publishing/monetize/pay_per_event.mdx
The following changes edit the PPE documentation based on feedback from @metalwarrior665 and also based on Discord discussion.
> docs: Improve PPE docs based on feedback

- apify-api/openapi/paths/datasets/datasets@{datasetId}.yaml
- apify-api/plugins/decorators/client-references-links-decorator.js
- apify-docs-theme/src/theme/custom.css
Improves contrast for the Client buttons in dark mode. Replaces the original SVG buttons with a logo and a text node. 
Removes unused `.redocusaurus` styles to improve CSS readability.
Expands documentation on the Get Dataset endpoint so that the admonition clears the `float: right` client box.
Closes #1949
> docs: fix client links rendering in dark mode
