apify/apify-docs

- src/parser.js
The targets from links were not parsed properly, this fixes that.
> Fix link targets

- docs/actor/input_schema.md
Change requested by Dan - will be necessary for the heading to show up in the new Table of Contents
> Resize heading from h4 to h2

- docs/scraping/getting_started.md
As requested by front end team
> Change Introduction title to Getting started

- ext/covid_api_list.json
added 5 countries and corrected source and frequency for Brazil
> update covid actors

- ext/covid_api_list.json
Added my Covid actor for Slovakia
> Add Covid actor for Slovakia

- ext/covid_api_list.json
data changed, there's no more "examined" data, as well the source changed (and might change again in near future)
> update description and datasource for BR

- ext/covid_api_list.json
Removed country codes and flag emojis
> Remove country flags

- ext/covid_api_list.json
A couple slipped through the net
> Remove final emojis

- docs/scraping/cheerio_scraper.md
- docs/scraping/puppeteer_scraper.md
- docs/scraping/web_scraper.md
Updating titles in scraping guides to improve appearance in breadcrumb
> Update scraping article titles

- docs/schedules.md
Quick fixes to structure. Added details: 1 second resolution and cron shortcut details
> Fix typos, add details

- docs/api_v2/api_v2_reference.apib
Add status filter description to endpoint for listing actor and actor…task runs.
@m-murasovs please check carefully as I haven't tested how this looks (didn't find way to preview in VSCode and I don't have edit access to apiary.com). Any tips how to visualize this to sanity check it renders correctly welcome. Thanks!
> API - status filter description on listing runs

- docs/robotic_process_automation/tips_and_tricks.md
A few important distinctions to preserve original meaning. Thanks!
> Corrections

- docs/access_rights/list_of_permissions.md
- docs/access_rights/organization_account/setup.md
- docs/actors/development/base_docker_images.md
- docs/actors/development/builds.md
- docs/actors/development/source_code.md
- docs/actors/publishing.md
- docs/actors/publishing/seo_for_actors.md
- docs/actors/running.md
- docs/monitoring.md
- docs/proxy/datacenter_proxy.md
- docs/proxy/residential_proxy.md
- docs/schedules.md
- docs/storage/request_queue.md
- docs/tutorials/apify_scrapers.md
- docs/web_scraping_101.md
- docs/web_scraping_101/anti_scraping_techniques.md
- docs/webhooks/actions.md
- docs/webhooks/ad_hoc_webhooks.md
- docs/webhooks/events.md
Turns out we had lots of bad anchors in docs. Should be fixed now
> Fix broken links - mostly anchor tags

- docs/api_v2/api_v2_reference.apib
Fixed docs based on allowing creating unnamed dataset, store, queue.
Based on PR - https://github.com/apify/apify-core/pull/350
> Api reference: Fixed docs

- docs/api_v2/api_v2_reference.apib
- Added actor builds and runs into apiary docs
- For now, I just copy and update descriptions of endpoints from Actors group.
> Api reference: Added actor builds and runs into apiary docs.

- docs/actors/examples.md
Updated this to the actual contents of example actor after fix.
> Fix counter example

- docs/actors/development/state_persistence.md
Preview/staging: https://docs.apify.com/actors/development/state-persistence?version=update/state-persistence
> Update state persistence docs

- docs/actors/development/state_persistence.md
- docs/tutorials/cache-repeated-page-data.md
- docs/tutorials/improve_performance_by_caching_repeated_page_data.md
Another original article, this one is shorter :)
I'm still not sure about the title so let's have it sit here for a few days if we figure out something better.
> added article cache repeated page data

- docs/api_v2/api_v2_reference.apib
This reflects changes in: https://github.com/apify/apify-core/pull/1348#pullrequestreview-582178598
> Add fields to dataset

- docs/actors/development/source_code.md
I tried to build from gist and failed, because my gist was only a single file named `gist.js`. I think this could be helpful to other people.
> Improve info about actors from gist and zip

- docs/api_v2/api_v2_reference.apib
- docs/webhooks/events.md
- Added build, memory, timeout params to actor run resurrect.
- added new webhook event type - ACTOR.RUN.RESURRECT
Reflects changes in [apify/apify-core#1808](https://github.com/apify/apify-core/pull/1808)
> Feature: Updated run ressurect

- docs/api_v2/api_v2_reference.apib
- docs/webhooks/events.md
> Revert "Feature: Updated run ressurect"

- docs/actors/development/source_code.md
- docs/api_v2/api_v2_reference.apib
- docs/webhooks/events.md
Changes from reverted branch ready to re-merge
> Re-add removed changes

- docs/proxy.md
- docs/proxy/datacenter_proxy.md
Merge after https://github.com/apify/apify-proxy/pull/118
> Extending proxy session TTL to 26h

- docs/proxy/connection_settings.md
Adding line breaker to remove scroll bar.
> Proxy: fix line length

- docs/actors/development/environment_variables.md
- docs/actors/development/source_code.md
- docs/actors/publishing/naming_your_actor.md
- docs/proxy/datacenter_proxy/examples.md
- docs/schedules.md
- docs/storage/key_value_store.md
- docs/tutorials/cache_data_to_improve_performance.md
- docs/tutorials/scrape_paginated_sites.md
Hi, I would like to contribute with a fixing of misspellings/typos.
> Fix misspellings/typos

- docs/actors/publishing/naming_your_actor.md
- docs/actors/tasks/configure.md
- docs/schedules.md
> Update resource name lengths

- docs/api_v2/api_v2_reference.apib
> Fix get run endpoint link URL

- docs/tutorials.md
The wording with all the parentheses and brackets was hurting my brain, I rewrote it a bit. It still sounds kinda forced, but I think it reads better.
> Improve wording in list of scraper tutorials

- docs/web_scraping_101.md
Changed from Zyte to BGWS. Changed text to direct readers to BGWS.
> Changed guide link

- docs/test.md
> Revert "Revert "[DO NOT MERGE] feat: for testing purposes only""

- docs/test.md
> Revert "Revert "Revert "Revert "[DO NOT MERGE] feat: for testing purposes only""""

- docs/test.md
> Revert "Revert "Revert "Revert "Revert "Revert "Revert "Revert "[DO NOT MERGE…"

- content/docs/api_v2/api_v2_reference.apib
> fix: api v2 anchor links typos

- content/docs/tutorials/integrations/run_actor_and_retrieve_data_via_api.md
Lukas requested the typos and some of the stylistical choices in this article be edited.
> Edit 'Run actor and retrieve data via API'

- content/academy/apify_platform/deploying_your_code/deploying.md
- content/academy/expert_scraping_with_apify/apify_api_and_client.md
- content/academy/expert_scraping_with_apify/migrations_maintaining_state.md
- content/academy/expert_scraping_with_apify/solutions.md
- content/academy/expert_scraping_with_apify/solutions/actor_building.md
- content/academy/expert_scraping_with_apify/solutions/handling_migrations.md
- content/academy/expert_scraping_with_apify/solutions/integrating_webhooks.md
- content/academy/expert_scraping_with_apify/solutions/managing_source.md
- content/academy/expert_scraping_with_apify/solutions/using_api_and_client.md
- content/academy/expert_scraping_with_apify/solutions/using_storage_creating_tasks.md
Also made some small changes to a few other files.
> Migrations + Maintaining state lesson (important one)

- README.md
Just adding a small warning note to the README about the issue @m-murasovs and I discovered.
> add note to README about + signs

- content/academy/apify_platform/deploying_your_code/deploying.md
- content/academy/expert_scraping_with_apify.md
- content/academy/expert_scraping_with_apify/apify_sdk.md
- content/academy/web_scraping_for_beginners.md
just some small issues fixed. Also, do we still want this big course summary in the `web_scraping_for_beginners.md`? I think we should remove it.
> Fix some small issues + add to course summary

- content/academy/apify_platform/deploying_your_code/deploying.md
- content/academy/apify_platform/getting_started.md
- content/academy/apify_platform/getting_started/apify_api.md
- content/academy/apify_platform/getting_started/apify_client.md
- content/academy/apify_platform/getting_started/creating_actors.md
- content/academy/expert_scraping_with_apify/solutions/actor_building.md
- content/academy/homepage_content.json
- content/academy/index.md
- content/academy/tools/apify_cli.md
- content/academy/web_scraping_for_beginners.md
- content/academy/web_scraping_for_beginners/crawling/processing_data.md
Related academy PR https://github.com/apify/apify-web/pull/1802
> Add academy index page

- content/docs/actors/development/input_schema.md
People are struggling to find this command, perhaps this will help a bit.
> Add a mention of `apify vis` to input schema docs

- content/academy/api_scraping/general_api_scraping/cookies_headers_tokens.md
- content/academy/api_scraping/graphql_scraping/custom_queries.md
- content/academy/apify_platform/deploying_your_code/deploying.md
- content/academy/apify_platform/getting_started/apify_client.md
- content/academy/expert_scraping_with_apify/migrations_maintaining_state.md
- content/academy/web_scraping_for_beginners/crawling/processing_data.md
Added better wrap ups for some courses which will not be focused on for a while (They have enough content right now), and some better lead ins as well.
> Add wrap ups for some courses

- content/academy/concepts.md
- content/academy/glossary.md
- content/academy/puppeteer_playwright.md
- content/academy/tools.md
- content/academy/tools/apify_cli.md
- content/academy/tools/modheader.md
- content/academy/tools/postman.md
- content/academy/tools/proxyman.md
- content/academy/tools/switchyomega.md
Just some edits to the glossary
> GLOSSARY: Change tools ordering, fix typos, edit overview pages

- content/docs/actors/development/source_code.md
- content/docs/api_v2/api_v2_reference.apib
- content/docs/proxy.md
Updates:
- Remove deprecated Single-file actor docs (closes #366)
- Fix a broken URL in the Proxy docs (closes #365)
- Update API docs - Create/Update actor sections (closes #362)
> Update actor and proxy docs, add sections to API docs

- content/docs/actors/development/environment_variables.md
We've added new environment variables to the actor runs, so I'm mentioning them here.
> Add new actor environment variables

- content/docs/webhooks/actions.md
- content/docs/webhooks/events.md
cc #320 (though this is far from a complete fix)
> Fix link, add info about resource available to webhook actions

- content/academy/api_scraping.md
- content/academy/api_scraping/general_api_scraping/cookies_headers_tokens.md
- content/academy/api_scraping/graphql_scraping.md
- content/academy/api_scraping/graphql_scraping/custom_queries.md
- content/academy/apify_platform/deploying_your_code/input_schema.md
- content/academy/expert_scraping_with_apify.md
- content/academy/expert_scraping_with_apify/apify_api_and_client.md
- content/academy/expert_scraping_with_apify/solutions/actor_building.md
- content/academy/expert_scraping_with_apify/solutions/integrating_webhooks.md
- content/academy/puppeteer_playwright.md
- content/academy/puppeteer_playwright/executing_scripts/collecting_data.md
- content/academy/puppeteer_playwright/page/waiting.md
- content/academy/puppeteer_playwright/proxies.md
- content/academy/web_scraping_for_beginners/crawling/filtering_links.md
- content/academy/web_scraping_for_beginners/crawling/first_crawl.md
- content/academy/web_scraping_for_beginners/crawling/recap_collection_basics.md
- content/academy/web_scraping_for_beginners/crawling/scraping_the_data.md
- content/academy/web_scraping_for_beginners/data_collection/browser_devtools.md
- content/academy/web_scraping_for_beginners/data_collection/devtools_continued.md
- content/academy/web_scraping_for_beginners/data_collection/js_in_html.md
- content/academy/web_scraping_for_beginners/data_collection/node_continued.md
- content/academy/web_scraping_for_beginners/data_collection/node_js_scraper.md
- content/academy/web_scraping_for_beginners/data_collection/project_setup.md
- content/academy/web_scraping_for_beginners/data_collection/using_devtools.md
Fixed all typos, improved Web scraping for beginners lesson titles, added a small note to the Proxies lesson of the Playwright/Puppeteer course
> Lesson improvements

- content/docs/api_v2/api_v2_reference.apib
This PR removes all mentions of `SOURCE_CODE` and related stuff from api docs.
> feat: Remove source code mentions

- content/docs/actors/running.md
- content/docs/api_v2/api_v2_reference.apib
> feat: Adding info that memory must be set to a power of 2

- content/docs/proxy/datacenter_proxy.md
Small text change to remove Freelancer plan.
> Removed ref. to old Freelancer plan

- content/academy/expert_scraping_with_apify/migrations_maintaining_state.md
I fixed the link based on other working links. The project builds fine and the link seems okay, but I didn't figure out a way to run a dev server or something along those lines to actually test the link in the browser.
> fix link to next lesson in 6. lesson

- content/academy/expert_scraping_with_apify/migrations_maintaining_state.md
Added an article to read to the 6. lesson of the Expert scraping with Apify course.
> Add article about migrations to learning section

- content/academy/apify_platform/publishing_actors_on_apify_store.md
- content/academy/apify_platform/publishing_actors_on_apify_store/monetizing_your_actor.md
- content/academy/expert_scraping_with_apify/solutions/using_api_and_client.md
- content/academy/puppeteer_playwright/page/page_methods.md
Bringing value to the try catch block
> fix: Try catch block

- content/docs/about.md
- content/docs/actors/development/source_code.md
- content/docs/actors/development/state_persistence.md
- content/docs/actors/running.md
- content/docs/proxy/datacenter_proxy/examples.md
- content/docs/proxy/google_serp_proxy/examples.md
- content/docs/proxy/residential_proxy.md
- content/docs/storage/dataset.md
- content/docs/storage/key_value_store.md
- content/docs/storage/request_queue.md
- content/docs/tutorials/analyze_pages_and_fix_errors.md
- content/docs/tutorials/cache_data_to_improve_performance.md
- content/docs/tutorials/integrations/run_actor_and_retrieve_data_via_api.md
- content/docs/tutorials/log_into_a_website_using_puppeteer.md
- content/docs/tutorials/quick_start.md
- content/docs/tutorials/scrape_paginated_sites.md
- content/docs/tutorials/scrape_websites_using_the_sitemap.md
- content/docs/tutorials/scraping_dynamic_content.md
- content/docs/web_scraping_101.md
- content/docs/webhooks/ad_hoc_webhooks.md
I am pretty sure you will not go through all changes here, but for the record:
- ~~`got` (not got-scraping, pure `got` examples don't work with `GOOGLE_SERP` - no idea why.~~
- Storage pages - let's quicky go through them tomorrow, I am a bit lost, should we use Crawlee storages or Actor storages there?
- snippets should be up-to-date, all imports updated to ESM.
- ~~TODO: should double-check snippet comments~~
- TODO: should go throught text/links (and here I am also not 100% where should be imports from what package :/ )
> docs: update imports add Crawlee, Actor import, etc

- content/academy/api_scraping.md
> Add breaks between consecutive headers

- content/academy/web_scraping_for_beginners/challenge/modularity.md
since labels are not imported yet, this throws an error for the user when the code is copied directly
> fix: missing labels import

- content/docs/api_v2/api_v2_reference.apib
Tested in Apiary, looks like it's working fine. Sadly, we can't use version branches with Apiary for an easy preview :( 
Also includes a couple of small style fixes
closes #413
> Add user usage endpoints to API docs

- content/docs/tutorials/building_public_actors.md
Fixing a broken link in the docs linking to the academy. Thanks @OlikEten, for finding it :)
> Fix broken link to the academy

- content/docs/proxy.md
> Add 502 code docs to proxy page

- content/docs/actors/development/builds.md
- content/docs/actors/limits.md
see https://github.com/apify/apify-core/pull/8801
> feat(actors): add build memory for paid plans

- content/academy/web_scraping_for_beginners/crawling/pro_scraping.md
For a beginner like me figuring out why crawler is not running takes some minutes 😁
> Updated sample code

- content/academy/anti_scraping.md
I'm not sure about the tone but I felt it was missing this general explanation
> docs(academy): add more general intro to anti-scraping section

- content/academy/anti_scraping.md
IP session consistency section was repeated twice on the same page
> docs: remove duplicate section

- apify-docs-theme/src/config.js
- apify-docs-theme/src/theme/Navbar/Content/index.jsx
- apify-docs-theme/src/theme/SearchMetadata/index.js
- docusaurus.config.js
- package-lock.json
also disable facets for now and add more search tags
> fix: ensure custom searchbox is used in all the projects

- sources/academy/webscraping/puppeteer_playwright/browser.md
> fix: Fixing wrong example #417

- sources/platform/actors/development/input_schema.md
Added @metalwarrior665's razor
> docs: Update input_schema.md

- sources/academy/platform/get_most_of_actors/actor_readme.md
Added Misa's Readme generator and mentioned possibility to embed videos
> feat: update actor_readme.md

- sources/academy/platform/get_most_of_actors/monetizing_your_actor.md
Added T&C for Store + note about price changes (allowed once per month)
> docs: Update monetizing_your_actor.md

- sources/academy/tutorials/node_js/dealing_with_dynamic_pages.md
- sources/academy/webscraping/puppeteer_playwright/common_use_cases/paginating_through_results.md
- sources/academy/webscraping/web_scraping_for_beginners/crawling/finding_links.md
- sources/academy/webscraping/web_scraping_for_beginners/crawling/first_crawl.md
- sources/academy/webscraping/web_scraping_for_beginners/crawling/recap_extraction_basics.md
- sources/academy/webscraping/web_scraping_for_beginners/crawling/relative_urls.md
- sources/academy/webscraping/web_scraping_for_beginners/crawling/scraping_the_data.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/node_continued.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/node_js_scraper.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/project_setup.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/save_to_csv.md
- sources/platform/actors/development/actor_definition/actor_json.md
Related: https://github.com/apify/apify-docs/discussions/661
> docs: fix imports of cheerio in examples

- sources/platform/actors/development/actor_definition/input_schema/specification.md
Hey :wave: 
just spotted some minor misspell (maybe autocorrect)
Here's basic github-generated PR -> feel free to use it or lose it :wink: :+1:
> docs: fix typo

- apify-docs-theme/package.json
- package-lock.json
> chore: bump @apify/docs-search-modal version

- sources/academy/tutorials/apify_scrapers/getting_started.md
> docs: fix broken link

- sources/platform/actors/development/actor_definition/input_schema/specification.md
Resolves: https://github.com/apify/apify-docs/issues/704
> docs: Added multiselect to input schema specification

- .github/workflows/apiary.yaml
- .github/workflows/docs.yaml
- .github/workflows/publish-theme.yaml
- .github/workflows/test.yaml
- apify-docs-theme/src/config.js
- apify-docs-theme/src/roa-loader/index.js
- apify-docs-theme/src/roa-loader/package.json
- apify-docs-theme/src/theme/MDXComponents/Code.js
- apify-docs-theme/src/theme/MDXComponents/Details.js
- apify-docs-theme/src/theme/MDXComponents/Head.js
- apify-docs-theme/src/theme/MDXComponents/Heading.js
- apify-docs-theme/src/theme/MDXComponents/Img/index.js
- apify-docs-theme/src/theme/MDXComponents/Img/styles.module.css
- apify-docs-theme/src/theme/MDXComponents/Pre.js
- apify-docs-theme/src/theme/MDXComponents/Ul/index.js
- apify-docs-theme/src/theme/MDXComponents/Ul/styles.module.css
- apify-docs-theme/src/theme/MDXComponents/index.js
- apify-docs-theme/src/theme/RunnableCodeBlock/RunnableCodeBlock.jsx
- apify-docs-theme/src/theme/RunnableCodeBlock/RunnableCodeBlock.module.css
- apify-docs-theme/src/theme/custom.css
- sources/academy/.eslintrc.json
- sources/academy/tutorials/node_js/caching_responses_in_puppeteer.js
- sources/academy/tutorials/node_js/caching_responses_in_puppeteer.md
- sources/academy/tutorials/node_js/dealing_with_dynamic_pages.js
- sources/academy/tutorials/node_js/dealing_with_dynamic_pages.md
- sources/academy/tutorials/node_js/scraping_from_sitemaps.js
- sources/academy/tutorials/node_js/scraping_from_sitemaps.md
- sources/academy/webscraping/web_scraping_for_beginners/crawling/finding_links.js
- sources/academy/webscraping/web_scraping_for_beginners/crawling/finding_links.md
only a few examples are converted, most of them are rather incomplete and some are dated and no longer work, unfortunately.
also uses node 18 in the CI
> feat: add Run on Apify button support

- apify-docs-theme/src/theme/ColorModeToggle/index.jsx
- apify-docs-theme/src/theme/DocBreadcrumbs/Items/Home/index.js
- apify-docs-theme/src/theme/DocBreadcrumbs/Items/Home/styles.module.css
- apify-docs-theme/src/theme/DocBreadcrumbs/index.js
- apify-docs-theme/src/theme/DocBreadcrumbs/styles.module.css
- apify-docs-theme/src/theme/DocSidebarItem/Link/index.jsx
- apify-docs-theme/src/theme/Footer/index.jsx
- apify-docs-theme/src/theme/RunnableCodeBlock/RunnableCodeBlock.jsx
- sources/academy/index.mdx
- sources/platform/index.mdx
- src/theme/DocBreadcrumbs/Items/Home/styles.module.css
> feat: remove last part of breadcrumbs

- sources/platform/api_v2/api_v2_reference.apib
connected with https://github.com/apify/apify-core/pull/12821
> fix: Added flatten param into API reference get dataset items

- src/components/OpenSourceCards/OpenSourceCards.tsx
- src/pages/index.tsx
> feat: Better copy on the new landing page

- sources/academy/platform/get_most_of_actors/guidelines_for_writing.md
> docs: change e-mail address for readme submission

- src/pages/index.tsx
Not sure how it happened, just noticed it
> fix: Fixed monetize your code banner button link

- package-lock.json
- package.json
Found a working (and still existent) version by the trusted try-and-see method.
related #809 - that needs to be addressed ASAP (we have only some time before this "new" version gets outdated again).
closes #808
> chore: ui-components version bump

- .github/styles/Apify/Capitalization.yml
- vale.ini
add new regex to ignore the word apify withing URLs add new msoft styleguide rule ignores
> docs: changes to vale

- .github/workflows/test.yaml
- sources/platform/integrations/gmail.md
change markdownlint to lint only changed files within a new PR
> docs: change the way markdownlint is called as GH Action

- sources/platform/integrations/webhooks/actions.md
This PR improves the section on string interpolation, as discussed on slack.
> feat: Improve section on string interpolation in webhook payloads

- docusaurus.config.js
- package-lock.json
- package.json
- src/components/CardWithIcon/styles.module.css
- src/components/Cards.module.css
Updates the `@apify-packages/ui-components` package to a new compatible version and introduces some small changes (ESM Webpack setup, CSS fixes for the Card components etc.)
> chore: update `@apify-packages/ui-components` (+ style fixes)

- sources/academy/webscraping/web_scraping_for_beginners/index.md
> docs: update index.md

- sources/academy/tutorials/node_js/block_requests_puppeteer.md
Slight rewrite to remove links to non existing actors and their KV Store 
fixes for Vale
fixes for mdlint
> docs: rewrite + fixes for Vale & mdlint

- .lycheeignore
- apify-docs-theme/src/config.js
- patches/@docusaurus+mdx-loader+2.4.3.patch
Changing the path to og-image because it was updated on the web.
> fix: update og-image url

- apify-docs-theme/src/theme/custom.css
- src/pages/index.module.css
Fixes this PR: https://github.com/apify/apify-docs/pull/891
> fix: Update selectors for examples cards titles and descriptions

- .github/workflows/docs.yaml
One more place to pass Smartlook token
> fix: Smartlook build token [internal]

- package-lock.json
- sources/platform/collaboration/list_of_permissions.md
Also, remove Schedule related permissions as Schedules cannot be shared at this moment.
> docs: remove DELETE permission from Collaboration section

- package-lock.json
- package.json
> chore: update ui components

- sources/platform/integrations/keboola.md
> docs: Update keboola.md

- sources/platform/console/billing.md
- sources/platform/limits.md
add usage overage info to billings doc
fix broken table on limits.md
add link to Limits section of documentation in Limits doc
> docs: add usage overage info

- sources/platform/console/billing.md
add new admonition regarding plan add-ons
> docs: add info about plan add-ons

- sources/platform/integrations/langchain.md
- update langchain integration as the Document has moved to langchain_core and ApifyWrapper to langchain_community.
- change langchain URL links
> docs: update langchain integration docs as the Document has moved to langchain_core

- sources/academy/webscraping/advanced_web_scraping/scraping_paginated_sites.md
- sources/academy/webscraping/anti_scraping/mitigation/generating_fingerprints.md
- sources/academy/webscraping/api_scraping/graphql_scraping/introspection.md
Also removed one link to Amazon, which is IMHO unnecessary (everyone knows what Amazon is?).
> fix: avoid redirects

- sources/academy/webscraping/anti_scraping/index.md
Embed [video](https://www.youtube.com/watch?v=W8r-tXRLazs), fix https://github.com/apify/apify-docs/issues/964
> feat: embed video

- sources/academy/webscraping/switching_to_typescript/installation.md
Not sure why the build is broken under https://github.com/apify/apify-docs/pull/837, but taking responsibility for merging the change. Creating another PR just to have a fresh build and to be able to add commits if necessary. Once this passes the build, it closes https://github.com/apify/apify-docs/pull/837.
> fix(academy): remove unnecessary exclamation mark

- sources/academy/webscraping/puppeteer_playwright/executing_scripts/index.md
The original text mentions the best practice:
> It's best practice to make this second parameter an object, as you are usually passing more than one value in.
So let's do it 😄 IMHO it also makes the example easier to follow.
> feat: follow the best practice

- sources/academy/tutorials/python/process_data_using_python.md
- sources/academy/webscraping/advanced_web_scraping/scraping_paginated_sites.md
- sources/academy/webscraping/web_scraping_for_beginners/challenge/scraping_amazon.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/browser_devtools.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/devtools_continued.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/node_continued.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/node_js_scraper.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/using_devtools.md
Individual commit messages should be self-explanatory. Each solves a problem which is documented as an issue on this repo. These issues are always linked from the commit description.
> fix: rename several chapters to improve orientation and fix a few small issues

- sources/academy/webscraping/web_scraping_for_beginners/crawling/headless_browser.md
- sources/academy/webscraping/web_scraping_for_beginners/crawling/index.md
- sources/academy/webscraping/web_scraping_for_beginners/crawling/pro_scraping.md
- sources/academy/webscraping/web_scraping_for_beginners/data_extraction/using_devtools.md
- sources/academy/webscraping/web_scraping_for_beginners/introduction.md
The individual commit messages should be self-explanatory.
> fix: improve stylistics and several explanations

- .lycheeignore
- docusaurus.config.js
- package-lock.json
- package.json
- static/robots.txt
https://docs.apify.com/api/v2-new
> feat: add new openapi specs with redocusaurus

- apify-docs-theme/src/theme/custom.css
> fix: Fixed menu item arrow position

- sources/platform/integrations/actors/index.md
added new admonition with link to Store presenting Apify's catalogue of Integration Actors
> docs: add new admonition to index.md within integrations/actors

- sources/platform/actors/running/actor_standby.md
This PR fixes small things in the example code for Actor Standby.
> chore: update Actor Standby code examples

- sources/academy/webscraping/anti_scraping/mitigation/generating_fingerprints.md
Close https://github.com/apify/apify-docs/issues/967
> fix: remove newsletter mention

- sources/platform/actors/development/programming_interface/actor_standby.md
- sources/platform/actors/running/actor_standby.md
This PR adds more information to Actor Standby docs based on feedback we received.
> feat: minor actor standby improvements

- sources/platform/integrations/ai/haystack.md
Documentation for the new Haystack integration.
Marking it as a draft, as the PRs for the Haystack integration page and cookbook examples have not yet been merged.
> feat: Add haystack integration

- sources/platform/console/index.md
remake tip about kb shortcuts into separate heading 
add mdlint ignore to ignore md001 before new heading 
add missing integration shortcut
> docs: add visibility to keyboard shortcuts

- sources/platform/actors/development/programming_interface/system_events.md
add admonitions
rework logic flow
rework structure & add headings
streamline descriptions within table
> docs: improve system events doc

- sources/platform/actors/development/programming_interface/status_messages.md
rework logical flow
add admonitions within code tabs relevant to respective language rework structure of the doc
> docs: improve status message doc

- sources/platform/actors/development/programming_interface/basic_commands.md
streamline the prose
restructure the document
use tabs component to render different set of prose for each language
> docs: improve basic commands document

- sources/platform/actors/development/programming_interface/container_web_server.md
rework doc structure
streamline the prose
> docs: improve container web server doc

- apify-docs-theme/src/theme.js
Removes the reintroduced changelog generator race condition. 
Fixes the `options.changelogFromRoot` bug when the default changelog is never overwritten (default changelog is always newer than the source changelog) by tracking which changelogs are default and can be overwritten.
> fix: remove race condition from the changelog generation

- _typos.toml
Add comments to the configuration file in a way I suggest here https://github.com/apify/apify-docs/pull/1141#discussion_r1749806422
> docs: add comments

- sources/academy/webscraping/puppeteer_playwright/common_use_cases/paginating_through_results.md
Fixes https://github.com/apify/apify-docs/issues/981. When updating the text I found out the examples don't work anymore, so I updated them too. I also changed some bits of code and texts, hopefully for the better.
I only touched the first half of the lesson which deals with Facebook, I didn't dare to even look further not to make this PR even larger. This was supposed to be a small fix, but ended up as pretty much a rewrite. Unfortunately that's something which I suspect will be true for most of the issues labeled as Academy 😬 
Asking @TC-MO to review the text, and guessing that @metalwarrior665 🤘 could be the best person to review the code examples.
> fix: update lesson to reflect changes in UI and in number of the repos

- sources/academy/tutorials/apify_scrapers/getting_started.md
- sources/academy/tutorials/node_js/filter_blocked_requests_using_sessions.md
- sources/academy/webscraping/anti_scraping/index.md
- sources/academy/webscraping/anti_scraping/mitigation/proxies.md
- sources/academy/webscraping/anti_scraping/techniques/fingerprinting.md
- sources/academy/webscraping/anti_scraping/techniques/rate_limiting.md
- sources/academy/webscraping/api_scraping/general_api_scraping/handling_pagination.md
- sources/academy/webscraping/api_scraping/general_api_scraping/locating_and_learning.md
- sources/academy/webscraping/puppeteer_playwright/browser_contexts.md
- sources/academy/webscraping/puppeteer_playwright/executing_scripts/extracting_data.md
- sources/academy/webscraping/puppeteer_playwright/page/page_methods.md
- sources/academy/webscraping/puppeteer_playwright/proxies.md
- sources/academy/webscraping/puppeteer_playwright/reading_intercepting_requests.md
- sources/academy/webscraping/scraping_basics_javascript/data_extraction/browser_devtools.md
This concludes my series of PRs consisting of improvements I made right after my first reading of the Academy. Closes https://github.com/apify/apify-docs/pull/938, which meanwhile became something like a diary of my progress.
> fix: typos and stylistic improvements

- sources/legal/latest/policies/privacy-policy.md
new version of the privacy policy
> docs: update-privacy-policy.md

- src/pages/open-source/index.tsx
> feat: fixed typo

- sources/academy/platform/expert_scraping_with_apify/actors_webhooks.md
- sources/academy/platform/expert_scraping_with_apify/solutions/integrating_webhooks.md
- sources/academy/platform/expert_scraping_with_apify/solutions/rotating_proxies.md
- sources/academy/platform/expert_scraping_with_apify/solutions/saving_stats.md
- sources/academy/platform/expert_scraping_with_apify/solutions/using_storage_creating_tasks.md
- sources/academy/platform/expert_scraping_with_apify/tasks_and_storage.md
- sources/academy/webscraping/puppeteer_playwright/page/interacting_with_a_page.md
- sources/academy/webscraping/puppeteer_playwright/page/page_methods.md
- sources/academy/webscraping/puppeteer_playwright/page/waiting.md
- sources/platform/storage/dataset.md
- src/theme/DocItem/Layout/index.js
- src/theme/DocItem/Layout/styles.module.css
Original PR by @MatousMarik: https://github.com/apify/apify-docs/pull/1218. Creating a new PR to continue the work and to work around the token issues which happen in the GitHub checks under PRs from forks.
> fix(academy): typos, updates and clarifications

- sources/legal/latest/terms/data-processing-addendum.md
> docs: Update data-processing-addendum.md

- .github/workflows/lychee.yml
change to fail on broken link detection
> docs: change link checker behaviour

- .github/workflows/publish-theme.yaml
We renamed the workflow in apify-sdk-python and apify-client-python.
> ci: Fix python docs build

- .github/workflows/lychee.yml
add continue-on-error arg to properly showcase errors
> feat: change behaviour of lychee link checker

- .github/workflows/lychee.yml
> feat: change lychee link checker to fail on error

- .github/styles/Apify/Apify.yml
> fix: fix Apify vale rule

- apify-docs-theme/src/theme/custom.css
https://apify.slack.com/archives/C0L33UM7Z/p1736507961527869
> fix: scope the sidebar changes to openapi plugin

- .github/styles/config/vocabularies/Docs/accept.txt
- .vale.ini
- sources/academy/platform/expert_scraping_with_apify/apify_api_and_client.md
- sources/academy/tutorials/node_js/handle_blocked_requests_puppeteer.md
- sources/academy/tutorials/node_js/js_in_html.md
- sources/academy/tutorials/node_js/processing_multiple_pages_web_scraper.md
- sources/academy/webscraping/api_scraping/index.md
Add various exemptions to accept.txt
fix initial issues within academy
> docs: vale fixes

- static/llms.txt
Adds llms.txt as requested [here](https://apify.slack.com/archives/C04URRT3934/p1737984069588129).
> feat: Add llms.txt

- static/llms.txt
After discussion with @vystrcild we decided to merge both apify.com and docs.apify.com `/llms.txt` files into one, so we can submit only one link to public `/llms.txt` directories instead of two for both the homepage and the docs.
> feat: update llms.txt

- sources/platform/integrations/programming/webhooks/actions.md
Mention new available variables in global context
> docs: Update actions.md

- .github/CODEOWNERS
add @mnmkng as codeowner of /sources/legal directory change scope of @TC-MO codeownership to /sources/platform
> docs: change codeowners file

- src/theme/Details/index.js
- src/theme/Details/styles.module.css
Closes #1475
I ejected `Details` component via `swizzle` command
> fix: details summary arrow

- apify-docs-theme/src/config.js
add Actor Whitepaper link to open source dropdown
> feat: add new item to open source dropdown

- nginx.conf
Related: https://github.com/apify/crawlee/pull/2872
> feat: add redirects for `crawlee.dev/js`

- nginx.conf
- static/robots.txt
add redirect from api/v2-new to api/v2
add api/v2-new to robots.txt
> docs: add redirect and add new item to robots.txt

- .gitignore
- sources/api/getting-started.mdx
- sources/api/sidebars.js
add new getting started page to API docs
add exception for new page in .gitignore file
add basic workflow to getting started
> docs: add new getting started to API docs

- sources/platform/actors/development/quick_start/start_locally.md
Small typo error. wrote dastasets instead of datasets
> docs: Update start_locally.md

- apify-docs-theme/src/theme/custom.css
Reported here: https://apify.slack.com/archives/C0L33UM7Z/p1744406697423139
> fix: Transition length

- sources/academy/homepage_content.json
> fix: academy links should be absolute

- sources/academy/webscraping/scraping_basics_python/01_devtools_inspecting.md
- sources/academy/webscraping/scraping_basics_python/02_devtools_locating_elements.md
- sources/academy/webscraping/scraping_basics_python/04_downloading_html.md
- sources/academy/webscraping/scraping_basics_python/05_parsing_html.md
- sources/academy/webscraping/scraping_basics_python/06_locating_elements.md
- sources/academy/webscraping/scraping_basics_python/09_getting_links.md
- sources/academy/webscraping/scraping_basics_python/10_crawling.md
- sources/academy/webscraping/scraping_basics_python/11_scraping_variants.md
- sources/academy/webscraping/scraping_basics_python/12_framework.md
- sources/academy/webscraping/scraping_basics_python/13_platform.md
- sources/academy/webscraping/scraping_basics_python/index.md
I made final reading of the whole course. I fixed a few things and I unified WE vs YOU with some exceptions, like admonitions, etc. The lessons whould be WE, the exercises should be YOU.
> style: consistency fixes

- sources/academy/platform/get_most_of_actors/store_basics/how_store_works.md
- sources/platform/integrations/workflows-and-notifications/make/facebook.md
remove unnecessary links from fb make app
uncomment fixed link in academy page
> docs: fix links in fb make app

- nginx.conf
- fix: Nginx rules change to route correctly preview documentation environment
> fix: Preview Docs Environment Nginx rules

- sources/legal/latest/terms/affiliate-program-terms-and-conditions.md
Effective from July 5, extending payout terms from 10 to 15 days and minimum payout increase from 49 to 100 USD
> docs: update payment terms in Affiliate Program

- sources/platform/security.md
I forgot to mention the Apify Console backend there
> docs: add console backend to the scope of the vdp

- eslint.config.mjs
- package-lock.json
- package.json
> chore: bump TS dependency and disable problematic `indent` eslint rule

- sources/platform/integrations/workflows-and-notifications/make/facebook.md
- sources/platform/integrations/workflows-and-notifications/make/instagram.md
> docs: hide make apps docs

- sources/academy/webscraping/puppeteer_playwright/executing_scripts/injecting_code.md
**Playwright** example did not work as expected (**I was able to** click Accept cookies button).
> fix: addEventListener code example

- apify-docs-theme/src/theme/custom.css
Closes: https://github.com/apify/apify-web/issues/5173
> refactor: adjust navbar item border-radius to 0.8rem

- sources/academy/webscraping/scraping_basics_javascript2/13_platform.md
- sources/academy/webscraping/scraping_basics_python/08_saving_data.md
- sources/academy/webscraping/scraping_basics_python/09_getting_links.md
- sources/academy/webscraping/scraping_basics_python/10_crawling.md
A mixed bag of indentation, wording, etc.
> fix: a few small fixes in both Python and JS courses for beginners

- apify-docs-theme/src/theme/custom.css
- docusaurus.config.js
- package-lock.json
- package.json
This reverts commit f7143d307cbb09b407b986b21f2b9574acedee4f.
> chore: remove Biel.AI AI assistant widget

- nginx.conf
- sources/platform/integrations/ai/llama.md
- sources/platform/integrations/index.mdx
Revert changes to slug for LlamaIndex integration doc
Comment out redirect
> docs: revert changes to URL

- sources/platform/actors/development/actor_definition/dataset_schema/validation.md
based on the https://github.com/apify/apify-docs/discussions/1963#discussioncomment-14572766
> docs: Fix dataset validation python code example

- src/plugins/docusaurus-plugin-segment/segment.js
supports https://github.com/apify/apify-web/issues/5333
> chore: drop camel case properties from analytics [internal]
